// GENERADO por Garmel/implementacion/generar-vista-previa.py desde relevo-drive/PDF.gs y Logos.gs. NO EDITAR A MANO.
// Es la plantilla del PDF oficial, copiada tal cual para que el inspector vea su informe antes de enviarlo.
// Huella de la fuente: ac06aff313
(function () {
  // Lo poco de Apps Script que usa la plantilla.
  var Utilities = { formatDate: function (d) {
    var p = {}; try { new Intl.DateTimeFormat('es-VE', { timeZone: 'America/Caracas', day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false })
      .formatToParts(d).forEach(function (x) { p[x.type] = x.value; }); } catch (e) { return d.toLocaleString(); }
    return p.day + '/' + p.month + '/' + p.year + ' a las ' + (p.hour === '24' ? '00' : p.hour) + ':' + p.minute;
  } };
  var Logger = { log: function () {} };
  function _nombreDeSector(c) { return ({ EZ: 'Ezequiel Zamora', SB: 'Sim\u00f3n Bol\u00edvar', SR: 'Sim\u00f3n Rodr\u00edguez' })[c] || c; }
var LOGO_GARMEL = 'data:image/png;base64,' +
  'iVBORw0KGgoAAAANSUhEUgAAAeAAAAE/CAMAAACpYuBdAAADAFBMVEX9/f0jHyDo6eopJSY3NjfW19hIR0lmZ2qlqKp0dnhVVliTlZjGyMq0tr' +
  'iGiIt8foDf4OF+gYPe3uCcnaC8vsCeoKNdXmBfYGK+wMI/PkBAP0EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAatbDnAAABAHRSTlP+////' +
  '//////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAQmiYpAAAH5ZJREFUeNrtnemCoyAMgCvIfTj2nnn/B10C2tpWxaOHdsmf3ZlpPfhISEKAzSZJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJ' +
  'kiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJViSo84cka6KIQLZOiBdtKuHqRjj8TrsPbH+28I3UdEum6ogCS212u4' +
  'MVQjAqpcyxl6xH3J9zKikTwh52RjveCfWCqAJSp6CcK1syBzSbLVSK0nJuzoF1auTPgP0BXTXWMkbpcKq4Xdo/nP9J5lCDUifOb5MfGFCdugo2' +
  'RlsrkDmlxyMDYwxSCOaucpKuh/SSziWzdsfN3oF+xciSRv+qHRxargAsHgM2d/JL5ZE5qqpSR3QdtsHAc25h0HZDNv2Fj7ejzumJeX3ePhGILg' +
  'sQhf5vtgY01qkazkaidboHrrIbTLcxKDCce7MP5uEoA+eW61IqXV/h5ilmW8tw1dP2v/WhtLHsSMcprUd7EgrAomm3Jdobi1/POXu4O/jdTp31' +
  'diZlVl2P/fyPcI0qmKR/I9Q2A7bUaa15ggMMYZdTaFVK6ilnrZSFOv9MvpHC/ydgp0F7JZyVHGuSqVPbp7u8YEacNndTpkztJ91U0+z/A4yQ5p' +
  '7tSLi/x4Lr17mj7sowWNDWkRluL13XGnl3xPB/BtjZRGMlHsvWqVDJyVv8UOR0OYRVbU9CSz4mklLXOO9/AIwcXJ+ywGPcqT9nH/WbYwzohbQj' +
  'lsJUHJzrNc5Afz9gB5cLOiqhCAoDjiz5zBPrXclk3mFsmDVxTUY2+08Ae9XNxqiup8vEp+BeIIO57mCcs925//F4/l8AJmduT9lI3c0/qLp3jL' +
  'llXU5DDoF4px7vbwzWdwJGP3o30jBnEAuJt4+6vW9hlKAdER2Wqj3jhcwx+3bAyIjjSLoOr2+xBQ4yinUE7dhZm/39E+vibqLk6wC7cIONp0uF' +
  'IUt9I+K8xBy3+hHOs76J4pCR9x/7LsAIObr56IFXcLLoORdEeJcaZ7kUvDLVyLR07W8CjLSdQJdajdbwbkXXvEh4BYRcJ2gLrL4GMOJjpnNrvM' +
  'ysZb7UqbHsSrM6xl2T2V8CGBEl8ZSRd2V9mNGubGvX238FYKRFPiabUYW8iqzvVXU34q8FTIwYrbw4P661lkULOQbx6gE7BzMbqb0uumC7FZcq' +
  'ETtCi1cOOOAdO/Yy/nS8vnLP11H7ZQ5N8Wscnlsga4rBRWRrBoym4ZXPMc6hKNUvXuF8ZwUUx0uoqHNyG6lCHZc8icIefJXeU4pZuRgYMqwYML' +
  'GjHWeYi5mfsgKuxtfDMl/6PCL2znMos2Wl3ZnRRSK3HQOZYhDi1QJ2Ye9o18oNvvM8Z2+IuRUnSXM8vnfd5FckY4qfh69WIgyk+TCHIXZ6pYA7' +
  '0jYx61zOSFpBSZdlRzms0HbQIhbALIU9DCm5ImE0urNh8cLQdQL2ce9o6yynZq2Qn34cgrZa70ApPZ2YrYUd2ZHSv7C0oVWbxSHmhO38F/Hdg5' +
  'moEq8R8FZRPEF9J0ZG6IfbuEUOC5RyygQsYrlzpPxPsKaNH4SgtGUFC1Bmat/N2IQejR8UOzYSrw8wOrMJox+WU7KSULfMBrAFlWW9ZRbNaxol' +
  'TmFZ2v11pN23z2ttq3ABt6h2f1C8OsDETnFq8hJNoMsFjestuEvjawUQ2ZXyHjL8nz5O4jtRWSdgN171EV4ZYGTkFL5Sje5HmsfGeexLuISdHH' +
  'dBKfTxsbYOP05Pn/MewBvU1w/XBZiIKdYZMzK25YOTjiN0xW72VLILZ+WjjaW3tWGE1o+CO9Ie3YTXBBgZNsk823F861rb3j4jmd09aTKK8OJx' +
  'nKf26jM0Xht3+WDHL5guRGrKNhmYqnHKu4v5cODwWvPUZbdkJx5isDxoMSLutXEM8EZ35QVWAxjxKerrBjQ9hq49RZQX/0n7kupLYsR9vRFlB3' +
  'JX/Yu7n32XrxowUXQKXiyGa9pWR5Pb+JXrlbbmQY1/5e/dA/R83+YrBkxEPk1/yXDtjcVEUKT62tJptC9jcVnft+16i+70lNyGGywH66+LWGQs' +
  '5JXi9QV6yGlxX1SLN2MJrwHwgIxre/J58MQvUdGMBi3etE64uwQ6BthZabxGwIjTSeYZ28H+TdRxlm+sv+yb58aj8wTLB7xthgmjxt9hGof2Av' +
  'ffwJn695bX6k4lxrGXYatbukIsnqa/bBhffaDRK729ALNTiWOAN2e5MsBITCucGMgX6Vh07VznT5RPm/bERRTwZr+u1YVITeQrB+U34tkT/IIK' +
  'zGGWpcgnAXaOFl4PYKImbuJL+TBLmC9Sfaugp8Wzx6Nt3qIBk4n2OcsH8b1bC99mB/gn6+P3jwMxHtJqx7UARsVEvtgOqaww0Tmj04fXpj2Gb0' +
  'MAr2YTlsl8MznArqJochuLjy9Oe8jgDQKMylUAnupfQQZryNXz5fOFTYHxeMAbna8B8GHqIQlDMhzI5k/Kk7zaSt8SHga46WctFrCZfAgG1d+i' +
  'v4+E8cAv0cUD1nQq3wEpaBTNji1Ef73L1IyWBgLeiKXvNkvY5JU/cQ8L8aj+sgUt/m8+LR79nWUCnpqghCZQYwxYV/y7qM0dGvZmKGB0XPaO77' +
  'vfyQv3aNS26ugOlr9mqd19KOCFb+k/fQAeMAIT9oRR/M0DFh0NGNW+2RIBb8X0lbcyuplyka1pAL4LKQYDvqjwEgGrGUuroyMwj16c7pfXJBaP' +
  'BUzyxQLW0wfgDJPB1m41Brr52MMBbxj1Ipa3g24xnW/GohFwti4P+mrV8EjA1YY/enGvwufsfRGbJoznxzBfIt8NkWM1eKmypTMUOBYjoXj+hC' +
  '50hzSFvwSwmsE3iw2fPH9CnuRDnkn+HYDJDA8rw5EEBYqmODBd6galSPj9BFYPuMhmDME5mavAWbHYluHeKV69As8ZgbNjZPyMZ7ixXmzT/PiN' +
  'L9cO2OIXDsEDMqA0nYj+Wk9ilgLHhuABvadMDF4q5SwFjjhIJLpBD85MYvBST1HO4ZtFVqsMcLFykiC81FHMZwGOVEMPmMM4pSH4pQrMZlnoLO' +
  'JiivmJkiSzxMxysaI+FpvdRZJ8MkaKxbBDBvh9gvBKYbP4Zrmem0NZcJrjG2ReFisaJenkRH9YzvMsdKwcawBgmgC/UtQ8vrEwOAH+tIVmcwFv' +
  'EuAli545BGciAV52FIxfC3iAD8dSIuuFwrPXAh4QByfAS/axYvXMAwDbBPh1guxMwPlhNmCVMLwQsJgLOJZIZgnwdwMWCfB3Ay4S4FUDjpasxy' +
  'er3gIYPV/+D8DR2Xq1CMCEP1/Q/wFYxDIpdG4XeUq4j/NnyzpmOV8POF5V+Y61tOaP3kiej8zgYfog65jGtq8GHI+T3pHJIupGdqoQktLB58Vj' +
  'Kri5l3UMwnMzWXE80UFYfqKlnJNEzjs76Mh6LBVZbbZtdi46iic6CH9wNil+cFNYnb7iZOrs2aQonm1sEMafnC5EJn6626pnQ8753ExHFE+07v' +
  'qz3kp8g/tVl/XOrbkbUBOpFt6A0R1EVl31ObtkB0dXjkWLRj6cq4xuILXqipNZ2ycN07/o2pgPj3H7/JsBz3ej44moA150YfSXA55bFz1A/yLj' +
  '/KfXB3854Nle1oAwNuanFgnwC+X0ci8rGmx/do+Obwcs5troeNEcOi441fH1gHdzUx3yJ+7J4QVHwt8OWL8+1bFBdMGB0rcDnm+jB+hfJJuFzw' +
  'nwCyPhuTZ6wIw96Z+0wSIBfmEyS84EPCRRERmFP+lHfz3gTTHXRqvZveiTG4J/P+DZbtaQmoz+ef9Pbun//YBnq/CQAsPIubUfPJTjPwCs57pZ' +
  'Q+j0T0x+UIX/A8Bzt1LKfoe0Qf/E+udU+KmAEfGytCIfg2fuhjZkzj5y9iU13wBYCS9qYYRn178PKn3VJ9wbC6P1A0YUe1ncyWdzR+FhYU6/J5' +
  '2b9QPmiz27sJxpo4dVr+96CX/Iz3omYLFYwES+YRR2sVJfY+Jiu3LAl3TOAg+n5HO3NBzUDKi3zDz/iG/yRMCXQGGBgNHMSaWBYQ7pHQsoXzdg' +
  'seQTwPXM2p2BYQ4p//rswAcIn59WF20uV1rkEe9mnieNB87ab22+LB02T9PgqxFcJOC5RnpomLO1tM8dfzvh6NKaoYAbkzaLBLzR8yaG8XFgS2' +
  'wVXVJGSzwJcFNBlgl49vkcQzclRLxfh9/qS8f3mBgIuJksWijgudU7f4PN66En7Mb0rdFSfBugYYBRc8OopQJGdh7hwRuTINO3ecKvfV9Oax8f' +
  'l4Y9zI1VWirg2244ZaHSYDLa/vUosdBvUmIy4FgwMt7SLxbwZjvLlca4HAwG8Z7JJczUW5RYD+jQgxY/ojJbB+CNnnfS3ZgNS86Cdt8rf4MSIx' +
  '3fZSeXgzyCuyT7ggHPJIzHZCrIQebdxuDlSkxUtJIFSzVoP6z7+GPJgDdazPK05Jgdws722KPEjJ/R67SXi1hU+MvssJc53482iwa8IcUswqOy' +
  'jWhfUFgD3nEpqV5jqJFWrGd88A+Ui6H7n+mH1ZPLBrwh86Kl46iVRqRXk3KmzNMtNTGK/UVWS8nBeNs2Ylo4YB8PTx+J8WlctpFw1o0Y57J8Km' +
  'KyV0JG9iL19xxqOto22lo6YOd/zMlaYjZya6ne8RBjKhR/iqkmmsfpwu1G+BGt5m7xgCFdjOcQHrselPCiZ/NXx5gpPqvaGHm4R5r3Vghj/Cst' +
  'H2MwSKtLunzAzvOfEy7h4+jddpGxLO9lLKxT5J8paA1XVjAoae1P0+TMjnTc2/muAvDMcGnCnBDSB0Z77WdOGVhrTeJHJsCpCqRGK+P7f2N3bT' +
  't6INAdBeWrAAwD8QwlnjQnpI0S/YydJp+YsE6ZK9D38kO0w8qVsqVwaOmAXorzXzllmEedVm4dgDcbzmYocT4pE4UItxE9rhSOMiaKwt5s5W6L' +
  'QjDmsA7etB8udCx3ZsIAj3jnTNRaAG+0ne5N41xM26d16/R4iFWt7nJzUsbIuRHXS+zO6ElhGOlpm9UAhhg1n+FM84kRLHKMYeycuzS9JxaSTA' +
  'h7cHCn+eb9O4mvBzB0VJlNznrQYnKOAoH3q8QAcz3aslApCuXQbtGMVun1T9YE2A01M9zpXJjZ0atXZfwcsm7Ydv6ZIT+z8ibRgwBWBRjc6ekr' +
  'l+DIknn9y6vywfnER/k7RZtdeAtkmScbHO/ZRi3W31YG2PXYkn5Kia8We28OyloX+3gvOTLEUvCyGYyzLqSqyb7Noq0NcHgrPFmJn1dE57MXIc' +
  '51QZF4lCpsgsMFtQuUCXn2MZK6/I03xPoAO7u0Y1MRY8wOr3jjakOMG3l1AlcdhzTCGgG7vqvkZC1+jp3+tBkju4HOyDoBw0w5+5s8FMuVI3au' +
  '8+DTDtcKOEzOTw+K9+vdcoqc7YgXXy9gZ6aMmIo4p2KPVmq6BB2TDFgxYMgVn9XU/CVUS6zuIDEE0x/j+vS6Afspn6nZLZwf14WYHMT4bOnaAY' +
  'dZPTkV8dBy4yU4VrbPs/rtqhZcP+BNqC3Gk+YhcC7FGs7kdXaqJzD0Fb379jnDrwDsHa6JWWqoorP7ZXsa3Fdxdcb1h72faES6LTb+EsCbUEeV' +
  '42lTAHLydPEb6NquGj0M5X+8MY2MtH1Q8+8BHGb0xETG1JnqxW29Cx6k7PCroFvahwoQtGf4ewEHxlBHNbGywprlMEawJq1r8tkXXrY/7H31+5' +
  'cBDowPkxjjDAos1BIYO5fCdpYW4F9Z8u76nrsTC74PcOVyMfmLp+mx4OdPQvYDTadh/pXMurGk7/l+bvZo/ErAlR4X08prfIEj1+RDPVN01hBg' +
  'eiwOmkRnlW/OpPhWwH4UI+ZghZyUAaFOU6Bi6n2R7h5Kvo60Q3Xzo1B8T4aVDJj8vwBcQ1alzCdBhiH5HaoMz2jBKndEADhYlBH1IMvf6e7J1t' +
  'o1IKOTsiA5PYrSHl7lXge9ZbKLbYZlAYZkZLFPYyel/wCwh/yjQZP/pkH2Ra6W759JGen9zlfhAtsuuExNLIe/bhT4nwD2TbrVZ66K06RECPbD' +
  'MvPrRmcW38I6w1KwI3jKnctIYfno5LUOsFkW/v8AV5RdFOLXlOGxKS9/Sg1os2RFaP0xzY/C4uAyVNqGI2/ab5LToLizzAWR/yngalSGYblk3d' +
  'YxypkCZ6h1dr7tvr2EPawh1WezUxZWGsoL2Z6xQADbZwwF9e7x/yXgi0o5i10p1LSJKMfklwJr74lxp9aVQDG0LUshgerfb8ReVMO8PcxapHQ/' +
  'DFMvAm3+Z/HV63vYMkNOxXwNqu4kzwdcMYzt5cHrLXqymXpHefZKMG8JMeDUVnY0e4N4Mw9em3k22iRdmP1iFO4iUw86z/FLSFcOuRu9zySx/R' +
  'xoY/iu3onBGdzZrHHY6cGqHed7ncgug7Q33h72Iawwc16THLFDQx7CKiGU2hnngjknCiWyS6X9QwC288kMaLcTZS/Cgojrb9Rhtztw4z3r568s' +
  'TPIO7W5IvaTw7tepoZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkSZIkLVKXGqTagi8V7TeeZyf15n6lTdjv3GjkfviP2tvswj7vcP' +
  'DgO/Y7RcZwWDfBej5D+BVGx0Ppcbs6Gsvo34lBvSmzyjL036gTg2p2dqKwnYti71lWQKDEk/U+1J/0ME7wUG0wEMvLETeE/dgLbs7nPVf+GLD/' +
  'AzBRLMeCG3023OawmGUBgIk6uYfaeRhWwkO1wdjjTA6GRGDDufrwC8RpluEnHTKilXlao5zVs1ufwGEhqvneCwCs4XiLsnLB0B4eqs0WFw7S0L' +
  'bVsNeavW6v5970KYCRZfL3Sa4Eh10TzJObGXauLq9vqn+zZ99iPGACu1eKaz8zMvtrAUxgrWkxjBKCFfTNwQdZ/BTA7lmdgjynSSys5nxu67vX' +
  'vFNZhXP+YcCogE14m0Q5bgPM4Qp0mJsF+6zhmxf7oc8BDLuoPAmwP0z5uYB3+f3jOcfl04D9Vh03molk3sLRH9CDD4Mx3I09xX8A2G+ZgPWdXn' +
  'wY8PaUPYytu/z8OKrmYB2zQcEOGKrsePtJLclt4uWypKO5wuNxqQd89sf/xe/NCYBt9am7721ufnP3Q/jNz/W+CHnA/PYz/m5X1+FyhZtPoa4D' +
  'zIw3ctvb9j1e2xYWt2ybX7y9wd1DN+/ZsgQGVsQ1tgLoBGwAm7x9KHJ81GBBz9C4g1wGv/fH/c3qbfNh931RFEKoagu5KhuiIBa3TLg/XLvCj3' +
  'Gfdb/RRKgNUqoEc8P8xxGqInfHyPlLwhr4gBcdIr/ww6WNYN8Vd99CQaSvlfJPKfwVqptpXronY8Uh5AGuNyAKbhAaxV2mKP39Htxj69/7DoTe' +
  'Xv1//zLFrj68vX5zgoy7IOw6f31ovfO7f0CqxP0f/nxz8IA2vhGv1+oCHPrxve/0eHw8omzT+tG2Ud3vzyQ6/qgkpZZzJf8o872FW+sXY24Mkx' +
  'L2vabSXIIO2N8NNsRheeFcGOvP3pB+3R5CB2thi4STtpQxF9tx/wEnuwC4gL/WCkXgvoJzLqi00JLhjAe/EjAA1kJSqdwHckpL7R81XI5pJpmL' +
  'HqX256jTkvMd3I/dqQHyV7QdDfRTSLi6e2T3/qhKBfkXoAf/Apiqy0MTI+GWOHe/c17vCf7s/n/prIfQiEXunhj1A/Z7v8VHNe6suHezfuNh3R' +
  'koYNs+VBwdQN8VnbXFuQr2BzbOxPy3PBMEARaufDnnMxtvi4nKs/LBRLuf/WAvqCGwMyN15k9f3RzkB+y8MhMuVAj3dRiwQLWJNhfbt6M488gQ' +
  'hyfgQem80T0xTVQYn2yO/7j3l2GPstu22Pr1wh1DLmIYwxnz/gmxqC0v84ewSU7APtJz/dBCwm6y7q2z/MD9/6Hx6zaFYMy/DBLuUYPKdQEmfQ' +
  '/V7Jys3nYp7mb5oQirzjiiekzYpquy+H5n1Kpfg9NXvUmJaf29EhdtThb1q+aVU34cWHrAu4bPEwBrxze0KjLuO96JLG6cLOL41g4vnDEe+phv' +
  'Hvg/pz4AQqea6x4/vKPxy733XRri+rPPBLJmKOW7trsO8QeK7Ko3xLlv5S3kh2g1heBtV+iLsAuluDR1eOpOwNkgwNy7YX6MkXMA+y1QTcN9Z1' +
  'fA1dP7N5SVycvrhiC56AKcnVC4FmDrAAxNEjxJQB2CgVsvWjSa3V60JfR/UfmNFHkr7C/kbcltZo/7ttQ9kaP/vL1AuXRt4p676u4BcLXvkb9b' +
  'NaizS5R6cG5T1bwI14NhF2A9DDDzmeTzH3Q3Mx0w8jugVs0YnDZ0eU3bGDRoBQizWiHUoVODbaO52wGH/4UX9l/h94D1b6Pvmktj+WYDdYJfOS' +
  'OCjln1Av6SdDhgdwGcneqEwqV1WOWPhrdG1RvWrqxsjHXwuNTU36l7yCVe6QJsBgEmlF09MjEdMPGKtm1GjZdHrjuOV5ILYEyZc7dRCJPaAft3' +
  'NezoM9/tgL2Cy8bl0T1gvwX+qaaNa+0kdXYHccZgCOF/WfDh/IbbeDhgN2jj4762YpeJPVY3lRZH79k1HQcPuEYp6v+HvqCvgCWabaJtFb0fso' +
  'vSTQIcfBbUBMwvr4nuAfvRCjaS+6P1cb9tgMO7Vr5SO+ACXzum89VP+iHRIZqRnTd8fpz2zRZ8qcqvq+smAuDtozXcXX488EoO2/BNdB2mmoAD' +
  'QtTowrUOPAA+1N//VeHSMAvsg9xZThaS1WDjmy+amvF6mhWbjgHhFrC6AN48AL5sWu4gh8x2K2Byk49pA3xjeWq3+Qawf4LLI7cBvmkQ564fHw' +
  'CHtrw8HWfCh39UNOIp903eDriZq4sDztnlFHlvWToB/+QDwqSdM5RB8BA3qz0OhmZtAWx7AG8aZ+QGB+UZgFtTlYMBw87sijHhDzy9BRxCTtHI' +
  'PqnwdVRnWmB3NSHxEwBTfbfLS38cXKJHGE0XC9f9xT9c1M3y4dTpvj1NK2DeBxhpezl6xN/1tYBFHLAWf04ppeWKPgK22Z1nrfD1F0Z6bVbcPg' +
  'Pwg1Xpz2TdT+Srm8bQlNV9JfigMTfLZo+TDQQetGUMNt2AQ77ZH2VQxy1zALM+wALfj8H+sveAYR4UY+uerGUMDl4WJq2AOfRTyt03Tf4UDR46' +
  '2eBz0XczID6t0XSxrirLsofooGMQvtNzC7FnixdNugFrW88LaDjJS9wC9lamH/DFIfUNnTcaXt8CJiHO7fCiG4B9Ms8HphfA6A5O06FpAKaX8a' +
  'gG7F9gAuDQiI0pDN0L+AfSNpm9S2uwWxeL3E4URac4d15jtjdWAFJg3l7UvcnQq7vcCthcJ7XAMylvAKPSdAK2jUyKBxwMj75+aH8DmAhCGomi' +
  'gPGaPri+fjUDFXKuAbAW93PmjZmbK2B9VbvaybJmGuCNvA1Sdgz1zgebhwwzojeJ5HMz4gmJltikIWJ3gRJy7hmvey+vXbeLNnYBFs378ppUyD' +
  'HRVsD++UTD7OZXE3EpGRTyEgfz4O/+hExW1QXKi4rcAfZUQzIyNATacHpTPOGUpdF4hwvgYFfJRUccCsknAt7dDDiIskhFh70fVi0ObFDdDfWN' +
  'w9UwEJ2cic+77K4/4pAB8Ddj1/YXqBdwbq9lCf6lr/kj5VvrAfA1j1G54KGtdPODKowetva8kLShYWs0/r+oTYPLS8zhldMNMII9TPlfgYmrrc' +
  '/rPwQ7fnRgzhMBI9H8km10Rf8sRjD+oG640e3ceAeAkWIi5ORuNoT3XbHK21smSCdh15X/qrJKX4IXUjzQAqH7wJvUTdcF2GndZTJI1fkgd/ez' +
  'KaltdbKqPLJzgixWp2tSCHL92E9PEpuHFwrxpNKGeYfZT+eYmp1oTMI1bG6Y0jcbomiYbeS5benZ4alROAM0GH4JD84IOp98JJLbwh+k0AGY9A' +
  'EOjUj9oeVEVJOIV8AM4zun2etXLqr5bJhyhdY0FPsY5q7mJMRV1bjSU1GGzsyfHVIU4kRxzsrKDrimgfOqd1Zi6mf2kT35mDJjzLUVP4ZIjDmt' +
  'Mn9WuCuIEg57q85gD54ZpXmBkD36joMlOzUKOP0cG+zZrvzUFZYnHwSGacgjO8m8mkFFhzxsuR6mBqEZMLUHOGG6mlgUFQzJjvVUrC9go+7yPI' +
  'zrf/ejFTICkktMFEzmGbUqjAcbcgqnXlLhmxvnTvF2LETTlLEKCZfh9aVUGyXD61Fny/nlk8IbMgUvA3XsUsKjasHCkzJpnNn4+3t4qBL7L5dw' +
  'jHh2FH8q+EBcwwy8ZLIy0ltxCrkO12wWZjb7slpIH8ojPIQ/5RY1KjoErHdg9VnMvCgLkLKEu9Y/CLXZC4L2ip3YSVzP5v5R7qUkpC6RunyxOD' +
  'Sqbs72KCWz2gUk/q9FgIPgsFb3TaWvNR7wyZPV15IL4bcDNtuqr1xvwC9NVcB3oGsa2DfaPpowROCUD7iOgnNxtvu658HnoWwDwSuAGTW2vn5Z' +
  'WQwj6td3UC//N41Phq6MyMHvWi34T4g3yvqz5w3hu9/Hgg3C/UMdhT+3VMM7c2EREe6b7va6Hq+rV3b/7JALl1W/t9Wxoe7dL29SMs0f0ONnm/' +
  'VJXTv2ItRS4dRepHX3i7tPtN6gr4Bs03mn2893v0FrU9y30eOz3zahEMNg3BW2tTxR2gt5icKlTo3wxYJEOkXnywmnJkiSJEmSJEmSJEmSJEmS' +
  'JEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJEmSJE' +
  'mSJEmSJEmSJEneKP8AXNRyBDjrsEoAAAAASUVORK5CYII=';
var LOGO_MINHVI = 'data:image/png;base64,' +
  'iVBORw0KGgoAAAANSUhEUgAAA50AAADoCAMAAABb9XCXAAADAFBMVEVcXymlllyckS+dXWHYLV/r4CBhXJiz7f+PbJRVLVuUbDCqp57bxq9kpN' +
  'nJZ3AfWqXYrYcYHGGemcB7fF01NxTpb5FtNYbbjBx6iTSXIj3Fs9XU115DNyJ4l1zG4N2MOIV9pb47LoDRjULoEDm8GmMeV1D///8kNGlmZmYn' +
  'NFcdNGn5/PqrBTjpFVAkLWqQmLAPSIv85APwpxPMDET3xwobLGb71wb0tw/W19jtmBfDzOQkLFbXEkkIU5i0tbXGydFaZYkaKldcXFwEWKSJiY' +
  'p0dHUcM1qpqa0zRHCwt8zQ1+vs5/BsdpWVlpbnuMfrli6vF0bsx9PZl6vPd5PJZ4ayJ1IVQ3pZZXjEV3nzxpFMWIVjaYvxtnFMVnXuplK6xNSY' +
  'o7fhqbqEi6q6RWry2uV5habrjBmmqsbZ5PPVi6L++tDShJz31q5DSnDw1Ne3M1zcpLW5OmP55tHBS3DDBz2YBzW2CUJxe6N3hJnpjSTtrGbrpS' +
  'qYpcYxQ1XrnUSRmcMsR4q6x+XyvIPrtjAYPIP++bMLYqzNJVTOusnrxy3y4y7yzKUrOoTw2Czisb7UmEv956+RJU2TGUhPKmkUVHOtET3Upkyx' +
  'VXTvxXPYlDVNNHCNFDlxGE7otkszU3blmrIxNzLz500oKzexaYSTNm331JPrxk3R9v5uJVdPJFgMS6Lp10q40dbKXoBJR1XJJWOpma3994716G' +
  '+tK2nxrMPshaP76I56kaRFS4Oy1/azuOLoDkxyKmoZSVPMyFYrV1KVLGtvhWZacXbUpWqMC0mVOFZsNndnWYXTtbjVtE9KO4P51W4ZJjpzhFXc' +
  'jCtXco//zeKTZzTblBlXRi82V4fdtjwra6QyRCq5dJBrZ0yxtE2xlk/YxDXUs2pjXWjY1U/S2m5urOWtdTttqNfcqTwGZp0tYpGlum/oeJmUsd' +
  'Ldpw/682xXZFVWHVMzVS81ea+NiVXIET1OgrWojKLtgp6Xd1V9GTuxiY/QHWVoSnuQyfKSR2hRls6uekzKm25hWVZ9gkrxAAABAHRSTlP/////' +
  '/////////////////////////////////////////////wD///////////////////////////////////////////////////////////////' +
  '//////////////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '//////////////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '//////YHuv0QAAVatJREFUeNrtvQdgG9eVqC2nt+27r//1vR+Xd4YeKJbHgTkSBgMRhSgqLqJNGCZNiSZim26xJdkmLStRFBdpbbmXuMSJ7SR2' +
  '8ifZNDvZZDfZZNM2vWySl7e9vu37trd3z7ll7hSAAEjREnVPHIoEMAUz891T77kbMkaMGDkxZYO5BEaMGDqNGDFi6DRixNBpxIgRQ6cRI4ZOI0' +
  'aMGDqNGDFi6DRixNBpxIgRQ6cRI4ZOI0aMGDpTxTa3x4ih8wQCEuSyLsLeMjfMiKHzRWPzssve+taPfvTLX37w6Uff8h32v7c8yv73nd/94qMP' +
  'PvjUU3cBocdBt/pPUN88CkYMnd24BOX41rs++tSDX2RcMnmDkjO43HTTTfff/6ML77osiuiq0EkNnUYMnelocoX57NO3oZx55hsSaIL88R+zH9' +
  'u3P3Tng4zQ1aZzzDwKRgydqWR+6MtPP82o5MKxPDPO5xvO4L+efRMD9M1XXHuZLdXuik9imtJp8ygYMXRG0XzrWz/4oWePHlVkApxnRpRniOhN' +
  'NyGcIEyD3nzRXZzPVYgV1YzuNGLojPuZH/3ys0fPPIuLxmeSTOF4hnwyQh+68alrV8cBNXQaMXTqSvODH3zHO44ePcqoBDCjeCYgVb7nTduZCD' +
  'qZAr2fuaCrcDpjhk4jhk6hNsHTfMfR158VkTP7ofOM7aBBJZ5Mfz500SroT0OnEUMnE2bOfvB/vuP22886qzeb6catEEnnpfDzzgsvM3QaMXQO' +
  'qyxtHrkBrfnBDzE0Xw/Sk843vKEXnpzOb4KNe+mlzL69wzZ0GjF0rtDX/J8STSnD0CmiQmff9E2mOS9l+vOrD914xWWGTiOGziFdzcuuvetD73' +
  'jH7ZLJQfFMo/Ob3PeEn1+98wpDpxFD5/C+5tHXx6Sn6/mG5T3P7WdfComVS5k8dKFt6DRi6BxAZXKtCb7m0dtfvwybg9F5BsIZep+GTiOnAp1X' +
  '3HFt/Ti4mmdp1mw3PgcP28rQ7aUP3WXoNHIK0Hnh6664duXFcWIu2IfecXuSyv5M237pBB166Z2GTiOnAJ0XPvjggxc+tcISHCygZZ7m0bN6sL' +
  'kiz/PsiPK84c5rDZ1GTg06L7rowQuvHNa+Fa7ms0cFcseHzjNidF5m6DSy7um0L2RyEciFV1w7mEJi5rAk87bbItT1i+eZwynPsw2dRk4dOt/M' +
  '4Hz0xs/+5IXhLMq+VOZlb73rqQdxoqaO5lmvPy6ep87nDZ811QhG1j+dlyGdb0bteSMTpkIvW5ZQ0Jh33fVlmEJ9W5zN1w/iePbEswed2y8ydB' +
  'o5lei88caLmdx888Wf/RESaqt62YwdymVCYz746KPQC0hi1Q+ZfeDZH52Xnr39zYZOI+ufzmuv4Hi++c2cTobn9u033/n/3vnZN1/41BV33SWa' +
  'V74V5K67PvrUl59+9Ka3cAnZPDPUn2uC59nbV1SMYOg0cpLQeYekk7meHE+Y8Lz9hhu++tBDdzK5/877Q/ld3q1A0BMFa1Vs2z7pfMjQaeTUoP' +
  'MOGbXldF58MdB56aWXnr1dE9FFRJHZnc6zVo3O7kmVlZUKGTqNnBx0XsnpfBDxFHTezOkEQEMJIVmOzpVUJJzZL50ZQ6eR9U8n+p2CTh4auvlm' +
  'btoyOlVTH43PN6Tj2WfCc6UFQxzRhy4zdBo5JehEz/PCkE7heX71BgC0t/Z8Qyxqe3xtWwXn9jsNnUZOATqvuOLCK+6QFQkiq3IxdzVviNq2Oi' +
  'epvudxp/MMOAk8l4sNnUbWP532FUzuuEPlPNHt5HiiaaurzrNXic7Xr4BOIY8aOo2cAnReCXheGCpPlfNM6M6zU3XnKijPM3vwecYZb0mwyXxh' +
  'Q6eRU4bOpxJ4bhdZleNC5+tjcHZtn3kG4Mn/0xuYbD/7aUOnkVOQzovCpMr2G/qhU+dzcDzPTGs7faYGZ8y4haQrw/NB2+Q7jZwidHLTlodtb+' +
  'xKZzc8B095is4mmmEL6x7x9QL/O5PvfAcqBR+FUt63/HHE+zz7jD8G5fmUodPI+qfz2mt7mbaDep5nDYYn15vwz1GG5bO/8akf/OC00/7i136Z' +
  'ya8x+ZmfOe20H/7oR1/8zltuEukUvvYR0mksWyOnCp0J5XmzhuelQ+HZZzX80aNHb/uNT33qBy/5Dxs2/Nn3vre0tFStVnft+kUmS2W6tPS9Jz' +
  'ZseM0P77/4Jm1Fsu2/e5eh08ipQCfH844eyvPSoQJDvWdhYwfqo0df/hu/+Qf/xy9/5tO/eO9ju3ax/3bt2oiyS4q1q1ollNL3f/8vfnjxxaLU' +
  '94z7DZ1GTg06r70imlTRlecNfdm23er5uuN5++1Hj4Il+x82/Nn/d++9W7Zs2bhx69aNMRGsHmL/WdbS0hPf+sZp99+0fftNhk4jpxidXHtepO' +
  'EZ0jmc8kTdmU7o7c/+5m/+wS//yaeXHkM0t2zd+t73bkwRoUpRiRJCl+jS90+7f/vZN915bcbQaWTd01lXeN6R6nnecOnQyhPN1yiVLwet+Y5n' +
  'n/3UaRv+7NPIJaK5dSsoz+6CdKJU6ZPf+u3ffclFlxk6jZxSdN6RbtsOSGcy56mrz7Nu/9B/Pu2XmZt5LyhNzmUoG7vrT0STWC5hKvSJn3ltxt' +
  'Bp5BSh865U5SnwvLSfpGf3aZ7cwj0LlCZTm596yYZPP3bvlt87HCrNvug8xDxPKyBHjhyyDlnVMt3fMXQaOTXoTJq2N65Gta3Mm4BJ+/Kjz37o' +
  'D37t08LP5CzG4ewOKEOTKc0q6k8Qy6INQ6eRU5POXqbtQCUJwCbTmUdf/hs/2LABPM2thw9v+T1Qmxu3HGY/tyQATYnbcreTaU90PoFNyyovLW' +
  'UNnUbWOZ1dTNuB6/l6NBj6z7/5B+hqRqzZrVvfuxX/4tJNc+6SOVAeGIIfhLhg5rp0wTd0Gln/ulMkVeI5z/SpKsv0SIjozqO33/7fX7Lhz35x' +
  '10bGI9eV3aSLWbsrzKpYUo6ACmXWLZ2sGzqNrF86baY8GaFXatM8L9SmqmyXSc9UOtNmqoiyds7ms5/6iz/53tIv7tp1L9C5UWC4NYXSnn6nwN' +
  'OKCvM/vYah08g6phPwZHBeG+LJO4BF6Lzhhn6mqmiAHj3r5e94+osv2fC9pSrovi3w35ataNBuOZxC55Yh6AQ+Zw2dRtY5nfZlV76Oac877rii' +
  'yzzPG7oEbSN9p0M8z7zttmd/8GvfonQJCmV3WRyvrYzPw93N2uXo3JhGZ9bQaWQ902lfazPH83WVL1x55R13XPiUWvLoootvjBTD99H+C+m87S' +
  '23Pf2S12z4WUoIhFl3bdn1V1Aru5UpT9CdqjxoUMs2lc4JQ6eR9Usn4snEn5io5HNy2YYwbHtT76kqwqQNAb3t6U+d9v0n6JNPUo8EVVCcu6yO' +
  '9RPv5ewd3vjnW9Lx3LK89kwzbcdOGDqbpZHxXPe3c+MjI83VPB7bX2mIzSojTHK99joyssoXZqS42rtcBfF7X4cThU6OZ53RyfisvC4sho/QGc' +
  'MzRXdCM4OnwdX82ScCAhEbh5AyA6pK9tn7DjG2toDy/O4rdy2jPAei06utHZ25HPzX7UUfnsFSpvdj76/ebczD/ipDbpfrgVIqnX6+ks83x0Ga' +
  'lYqfG3AYGZbOfEU7bN5fTQxyJwmdGWbaXnZtnsE5P1HJVr4A9bYPhkmVm2Rc6IZexu1b3vLoF3902ve/98QTZbpEPCzocYhL3Oq+1q12fbrzOx' +
  's3/tXvfO2xZ57fcnh4OpNh28za0VkaYQDm4y+WiiPFnHzqiwNuvSKNxPY3vup0pqOEj7ImxVJlLegcjx+26a8mncWTgs6M0p3z8/OV7AcqX3id' +
  '1tw2DNumRoawZcFNj97/w29862cZmWWGjGsxMGtthueUReb4qp/7d23csvH5Z2z7+d/fIgK2MUaXN21T6KRrSCd7PErxxywPGpPfZHh8mstYlN' +
  '3N3vHxyhBj/1rpzjid8GT7AzBWHBl2BIpIaajx6CTXnZl6vX7trUAnsyQqMzPZbLZy9U++GZfC1nqY6Cuq8ObTZyOYX/zhX3z/W08woTRArem6' +
  'xCo/Zy8cqE0Rpt4mGJxzWFHw+8DpM6/8Z0knr+M7HKdzSw86Y3i215ZO9pg1E6+Jm+znx3uqxnyz+8ifZ4wP+tzlK81hVPGq6M6RQcz04XVnk1' +
  '/yiIyfcnRmonQuHjiQHR8/7V//9SdhpfobL7754pu3P7R9+1f//b9nkH7zm9vhD1gy8OKb77zztG9s+C/AJS0zYSrT8xzgk9DnGIhZqIitZtlv' +
  'B4HOWwq2XbcP/tXGw5BY2bIFtejhLRuHVp5VMrnGdMbuqHh8VnyTm0wrj6/N7a8MTWczx8WvcCuidNzpxC3z4rD5cX6x86ccncy2RTonAM4Z1J' +
  '6z6Iv/3Wtf+5Of/SyssfvVr94A6hOWxb7zzs9+9l9P+5uXbvi3J558koHpeXzaiOWQgBISMEhboDBtZufussqdWvvAM49t3HioWmNw/uOWjYc3' +
  'bn3+FVt+//m/4qbt4YHojOBZbqw9neNJlbLimzy+ikph2VhlcUg6K7aUOjq9/X7tFdKZU4fNlUCPlk49Otldu5U7nhVBZ3Z2bq7RaJRKpZe+9G' +
  '/+5l/+5bdf89u//eP/8ppvfOMbr9mw4Vv/5cknQWFSarkwH5p4LhSmM53J/qtSsu8gXs65oFre9e0/qhLyim8f2mjN/VH7sc5vMUv28JaD9sQz' +
  'r7yXqc3DGzeuwPMk42tLJz4evh7pwfF8mJscCf+W0unsst/BXtY/UU/Tnbl6f3Tm7VDwm+f1b5Pr+iWbxfgu631eMNwypNPGLMhIPzvK5Yags+' +
  'tGuT5vY9976X563ejEsBDEhX76AwDnx5jM7d/fAEJHRv4Hk38rvp/Jq9//asSSEBp4FEOzAZFBWkZnAEYuLdOOXdtTnyJo5oJehWK+Xbs2/vmP' +
  'bWQU7trPrvX/vQur4g+nBYa29Kc8ycza0lmMpE3yMoCJ17rJBJ9XZnLAR3xu9socqA+miNxQBCNLsIFfYX8Wi6USpA3GlW/aRABKYeCnybdHuk' +
  'p5/Ft9OFcpcQ+tayw1VxGHLEWeSp8dpih2OACddV+LgeXGRZwo6gfnmyXNZQxfHo+FX+F7qNfHk7qzrg0K45ofkRdjY6mS0+8HOx9+6ca1A6jf' +
  '2c0p8T8idPrNceHhhsE5X0TqmkknO8/PFO9wMcxy+/K+anvJiNvOblAJong5PBRemNQwRDqdHd/3pzmd8z+dzYL6/NgcE8Cz8LUCk6mp9tTUVJ' +
  'XPfiaY0UQiHcxsQiyIqU9m1pJFWi1Xg4kOe22Bve3eQsgth245BHSJGdcbv9aB8NCfb9lyGHKgh4ems5xfWzpHEIK8buoyrooqZovvoH6tiIBG' +
  'SQY3Q52VG9GCHU0R9lWS16OVxTAwi1uJD8M+c5oPJjkodo3jjvNTH4ma4jmBphaM7suyZUZmiNJ4Mfw6pVzcDxDXTO7SL4lPsyOPh4OeL82Q8W' +
  'S0V9OddngR8/o1E8NEBXbOx4qS9nJEzasrpNM5rp1qSYKYxz00xXWrx333kl9Sl7QifAYtoq1uA6LtiyvUzCwX4UqnszY2jXROzFcqlfksmraz' +
  'gCcozwKnc2rq41UQpNK1BJpitggKs11pZ9FzGbuLBXiPWFULZ2Nu3Gghm1ugGv63XvkMBm9/jPmgh7WC+D6amETorJLcmtJZLFXGw6xmBY1adZ' +
  'PhXuVDaMP7xG93Xg37Re2hZTexEg1L4i7gMRPPO/tXPU2lJjsF9h6MB7nwoRvX9sDeTEnrhPvT6fSjOZJBLFtbZVtD6otawjenRoOSrjuxbEhd' +
  'mlLIi9xDpZffadsq4NyMXGRhzuT5wcQh5O3og86KtjPlT6OCVJc2EffmA5t4N9TG4X2vhAdsytfzchSSd3cAOiciSZVZkLl9QGdL4XmLopPwDl' +
  'yuDme5CpewgehWmUaFSZhlQBTxFH2kGXnfvfexaftj9/KqW55bGYpOa43pBLVZlGNeDn7LhwVh6o6ESoOrFT6GV+Rd5DbUOLNnx3FTsKBQy2IY' +
  'Ds2uEjq4lUouz/egR6DkwxLmO/PCwMvnm11SHdxILuXz+UoztGzrYjjw/UpJjeT908k3kNZlJR/BkJ9os8KepvFQd/LPlPJ+vhmq+ZGk5dCVTq' +
  'k78dqzcaiSb5ZC7VVRF17Y+SNRICOo6nT6kYFEMFPRR50knZqfILcYUeNp9Eroo2IzeqhKf3TmmGGLupPHbYXyZNozxBPonKrqeBIlDoRqmSsK' +
  'd3CcMlfTCkCxWqIJEDQ1UIghfD/2jNYvM60BWNfQEPb/kpJZY8s2z4d/pAyTCpruHNF1p/CGmuo+CadIMCENpXy463EtrMroLNWlp8Xxzomb3v' +
  'RzOT+v0zmiodNMG5H5w5eLqZ8MjgmV0FDFV7vTWdTprI/wDK1fRL9bvKZOiZ9G6CwqTtj38sPTKGmPb7NSz+XymWXoFLUf45qlndcuMQxqeIB6' +
  'ZSRyffI96cw08zmVIiuKu5MXKriSZxfcT9LJPOfwQLhLVWvow0UR5EkMITEEUYamKIOsl1KVZxc6c8LxBNt2RuGZoHMhpDPUmUgm+J8LeL1q+9' +
  'xAINuVzu/+40aY7/lb3wVPVNIZB7QLnYdWXMi3Ajoz4mEADxAMzFIqneMRtaVXAeSSKiJOZwn9Jzt85EtKd1Y0YITpho9CU9NppZG0xIQfNw5x' +
  'h2IMgGgo1/x96k6fHQVMaCTc10OqiriiHacT6Wnqr/pqMEvPqMRitmyjEroHxVIIPx+RfHmJ89r35K5tH3Tq1woGEHHDSiPp2dXIgSopHmSuqN' +
  'ze7iUUI2mXuhed0yJsq9EZw7OtK89QMJVCpvAezRSmgByealF4RumEOdhQk/D89K4tv/d7W8PavuVqbQ8dEsYt7rj6ItCZB3bysnCvi+4cj9Qr' +
  '6HTCTU+kYKJ3EAJNFc2Ywzq4ONUqKtSMKJh8SsJeV2QhnRU95FKXKrpLchKiX/kIJkU8DASxS3acQ4z9NBN0os1n60es8PGrWOor32nnxFhXgR' +
  '3lExEqDJmpb6TGxeIgdNbBGAgdBr9bRUfs0o2k+BLjod/ZvWprYDp50jOGp1Kej3XDk7mX+wrtWbvhBZhDUapTKE+NTt67BBZO6diLz7zyJ+L1' +
  'CFth4Yb3pqzdcOiQ8j1xx4UXgU688kUZHepCZzNxC0LdmVK1F6ETVUyIW1HTubm4OpPa2bbjmHULuCo6S7r+sUvirNLpBAO2lI9FZ0o8NBUOJP' +
  'xc2QNdieg8tcto4FeeKDro/dEpky7NaKZF4pHXbA6mUqVVMxCdGHwL6ax35yry/eLjbTOiO/M99tJfVEg3bXsoz3aq8nQxPMt+UmoTilEhzSm1' +
  'oqYtp48pzu/+2PMQuv3u4T56f0UbgMm51/vWls4SXmcemysVwz966M68nNyo7gUPrFa609kMVQxzxZojPeisyG3DJxiMvvEez5I6DzS+hPbJ5S' +
  'RCXS3bYghWnef5RoQFV4lWC+Tj9MhdaqME+165YlHROdIXnT6Pt1TE63ZCZcPgUIx+0fyglm1Opcx6FCSnHMjvVvzVnc7KwHRKPBe7e546nTRU' +
  'nEHwbewEvc/BOC6xAiuOp4SLV9Zu3PJbz0Bi5WM/sVEWxR/GjkOSxVuUHDmUWjJEyNza0ilsRhEgL6nntgedlbjuhFdK0Sx6bJPxkXjxdzGNzl' +
  'IxpLNpR5RgKTaOF1PozMXnnCxDJwaVoeJifDyMN1ZipXbiGozD4JWER8tBFCFsUkS/sNSbziIEsmGOJyYj+VA3DkmlFDojg4KvD1/90eln8pUw' +
  'xtODzuR4l49EWPOl5ejM1SvNgeis6XjKcr5enqelqc6AtLM0wF8doUfdKJyWXJpz43u3bmS2Lczz/CP25Tq7lFUL/74XqKyShx9++J574P8oD5' +
  'MjR2J5FTRuF9fYshWFCKVYkqun7izF6GTPFj6buoOYCCSF1QXFUlHSVEy1bGN0Jr2gZqruzMXRXJbO6Aal8cRjaqPVnufp1ZEEPJXI8UpKdxa7' +
  'zrwbT5whFC7wO9GM0cldek2l1QejU+SaRsRX6DnlrxIGqjWLQRVtFXnJxXgynyM+Mx5+qT7pZJJKJyjPiOeZQifxKKW1CUrhJZhzbXE+43hGAk' +
  'OgJ//Zns53fgcaT8NLoCWPfOlLX/r85z//LibXXMN+/BLKJz/5eYar2NmhjSpku9Z0iuucDy/+cnRW4hkVTXuGscrIJtEpjSOgOuSB6kk642U8' +
  'Sbwwo15Pp1M99VBEuEzMNjqVq5JJo1MLa6erNq1QRpQtLmfZjsQyhhkei9KMeamEopo8N4Blmysls67gxZb8PnRnWLVVEZUQfOxN1508twzOTb' +
  'F/3dnhdPYTtl1Iep77DmRnbR+qbx3HSUSMJJ1WLGy7dcvv/OO939745xDB3XjLlx7+/Lt+6ReY/P9c3rZZyvnnn78D5Nixd7/7nnvIkUOHDh05' +
  'QpguJgdfjKiQeGwymf50Z9yyxVsknzt5C0ua/uBPYS5WWN41KhTzO/vXnWAZJw7T3+xr6TYPRCc3GnMZP1J234vO+PxOWS4b+8oyQpdP0lnpXS' +
  'ukhlBe3TCez+c11AawbOGC5GS5XiWPtKdGhca5YmVDoV8ZjM6cnwwMpVQkaMrTkqpzgic6swEhKXQqPA/Fsir/vGULdy8XFv7d//Wua972ts2n' +
  'x0UiuonJfQDoJ+95+J7/B6oEd+0q114kOn1VVz0cnVolPN+kqMpOtRRpZlk6KzK6U08U8XSlsyhjNKW0mtzm8vM7NZzzeiZV8ztLxW66M/2y9t' +
  'Kd+cRRwZOO+J1FDf8czCGOuIPg4YZ0si3jutMHYor8GtZDv7PYlc4K5JNyegETRAZEpbH6zmm6E71nkQwaIGZbBzqXz3kinUp5qio+injWG5S4' +
  'hHSnU62JIkoStm79iSOgMrm+/Pu/74LmJimb70Mdevfdn7wHd1q17ReHzjRoBqRTzu0Qxapa04VmanZ+ed1ZjyQqIs9SKcwOVuD58LWoUgoQXa' +
  'rgU2Ib0ZitVDzRWKuEx08PkBSLy8RsU18vjsSmsyVUmqIrkgGGKx2vs0XdK8YY+EbLx2wjBwKHlZnAPnwRvT4qjc4RLXA1IJ213jnPlsLzsVB5' +
  'Ip0BpTDpBOeVOamAJujkMdkjr/h3n7/mF/4+qTFDOtnPT3xC8bnpOiabdtyNJi6hz5zMdGqfjORAISRc7J9OmH5StBORylghXzOePw0LhvulM9' +
  '/lmjQjDmBJOoB+xC2UNYxJxEdK3S3bLuqrghMBIuZCKROPCulp1mJYZ1vU/U4/REYreCgNllGB0ef9Qi3WtaluKZZtTktj2QNYthgWiuQ8e9CZ' +
  'sG3prD1fq7ehoi/orTwVm0e+9MlPHruGac3NXdlM16HX/eV9o6OjO+5++7vf835o93kS0RnPWau4e2QTXprXt2XLpzOFKJQSDbkwTFFPTPMopn' +
  '2fIegc0ZRYUSUew5el7uxisi+nO1MKArC/Q1MfkNARjhZBFPWywohT34zUWvG6QOnG5oqDZlTqompvXK9ebKbrzgpcIX8IOjtxz7NXtW0YFxK6' +
  'c7HqVTswZ4xUe+F5CMtkjzCt+aXP/9Iv/DdA7mWnn/5f+2Jz819K83Z0lCnQvYzPV+/JnMy6M6celehzi+mGuJIJC3pjwKAtVtJmdiXqbEe0+t' +
  'a8mqOST226kt52t2sDwKYeMa6o7zOiV6mXZOlvM6Wp4XJ+Z3rTJmkg1pVh68ehKUXuR1EPoTejF59bLpy0cNZBLzojlXwyz6OXSKArWkw+NThp' +
  'IK856YkHqiedum1b6bfa1sIZKQxMnJtStRSPcTrJoY27LPLwPZ9897Fj5+9gyvATp2/etLk/xRl6n3s3Xcd+oNx93s76SUZnvlQRAY5cSc98Qz' +
  'U5dNSSOX4xdT6XqzRL+W6605dol7j29EENJMCuiMkWdd5CQXa7RGqKfHYGOww2dJCtF/x8f7oT9Q4PSonZGmL6C9YOVKBDWGkknASHAUtxxHyl' +
  'OdJPVCjXpcyGfYu6qr0tqUvMn/06gF0qSQsFjlrP+M2imD6f53Y2c0H9vI/1v+h31vm0VLZnf3ndyVWgmOwtX2xqr42ohFHU78TAUb0i0sY5vx' +
  '8643GhifmZSEXCvh50WmJGigtdhQLueFr6xE/t14cf/iQjcwfH7fRNm162aQCzdjOAiYSibNo7+sg76ycRnVeqrJ+suCmFrmH4Qmkk2SWyq2Wr' +
  '0h2lcX1WY9SCLkZLD8LyPP1lX5jVyWYA3emUJQbNaJuCkeg0RtHPthLNkBSHpjPD2yuoGbT8Q7I5S1MUFhT9yCnq+dqMKJnAM66Izca1SerL0w' +
  'n3cLwUHl7cQ3Hwopx3H71yJZnqDWd7N/uiMyPp9Kd5f77X6njuAzxbqtpWr4VnRMIPhzhygQYVzQ3VqOUwec973n3sbiRT8LZ5cz9eZzx0i3gy' +
  '33MUflx/7O9OZDrhHn9fN5Sa/xZpnxy5a/LBqY/HmrjCa6ClcqnA+Ho75tR1FtR7pWIppTeCoDevn4nfH51aBZD+vSsjqZ1LKim1BUPRCQNOKd' +
  '5aN69BqLdn04saxtWB8+Jj4zIXIuaijwjnoNK9n1sltbOv1ht7PKcmhcfn/YkDMcXOG0/FvntXOus17FYqdWf+tSnKUwaGQjpBUTYmqAdlCIik' +
  'E6rTUGU6nveee94NbEJcZ5OgrU84k8Yt28eolOv/4+e21deEzqKWN+ubzsk/4Y8m3NH/4fNuXuylydh0zVJJtiHSTDc9999dd0KfK9Wxo5j6oP' +
  'uyvqzkZ/S+Qk05zAOfovPXeLGUYLEHncxUL8WLFMIEP/N3c368r1AxUl3Qo4d+Dzq1yqOSbLuVDyFj30HrcSRVHBynqcDNj0gQ0RQtiooQ2Rct' +
  'v6zuLIruXWoOt+yUIKfpyMqMvH61imGtVTE5mnalM1PviJwK57MSNkmQ/b9agCfGhT6+IFOeVSvI2gu0sa8aRF1NzqjjcK359ruZ1tyxF8na9J' +
  'fIGkduADo3p9HJ+Lz73LWgM88kl/oq/6Ui3oZXlObJyffVL9C7DRfu+UC0z1uFmVaVvBpn/Ap+qKl2FW6fiR6P7x3K09n2XU+eWVxN3Hs+r32K' +
  'uZtsw2ZTOzBvRuf3890z+vdpxrbJq/NhJ1rRj8gXLfLFEdlj1m39Ij/+naMHqPALlNOhKTbZdYMrGd1RM/ygX5G9DNlvvHwRG+urAhP2KkxQyF' +
  'W6Hhx1Z6UCF25cm8sgdpiTVxF7FFbiVw6ui2zHx7bPZ/qkk2nPPb6fe+45VZEwz+kEPHnzTI1OjmfVKhNaset2rWpFXE1u1gKZ9zCDlrF5H7NE' +
  'JVt/uTmUAZTnplTlObrp+t31NaDTyAku+bVqIH0cD9SDzj1MarnnphWdi4sqbMvpVO352kAnuQXM2jGMa7dJHE6YgA1K8+13P/LIfZCj3CvqCT' +
  'ZdJ4M7gyrPdDpHd5yXMXQaqawVnT2K/I4rnTt3MuWZU/VC84th/y9O59f0DkOQ3iQkC3TmaRClE7Smh2xeLxjai4U+jKXN16nSvBUqz008NnT9' +
  'uYZOI2tH54ujOzN7dt56K0Rt+bINaNtmVc4zqjynPv5xGbWloDsXqiQAOOXkLufVr3772//2keuvv340Ivfdt2NzBM6h40IKz+vvPsfQaWTtLF' +
  'tMT9dfBDq3bbuVAcr+L5fz/EC3ioSPf/yWWwjwSQv2+ML8C0E4Z4VSjynNX/mVBJqMzft27I2wuRLluWN09Lq9o6OPPLLN0GlkDS3bF0d3ZnYy' +
  'PLd94QtfEHhGC4b2RZXnY7d8G+kkc/NQ/o65FbRn//TtDM0kmXv5zwScKzFtUYGOGjqNZER57/q1bOsZfxvIz//81QJPyKrElKfEs/1Y9ZZbkM' +
  '4pWBbQcXiA9p4/Ba0ZAVL+wSsINiXoHADPSEVCSOfXDZ1GRPnryX2gnrrT38npvORqJv8JGu1LPLNiTZVw2QaG57fR9WRuJixD9jDqzF/5lb17' +
  'Y+pSlwhemwahM4nndTzKNDr6t3sMnUZg6kqx5K/BgaB/WWntdWfdB9P25xmdiOfVAGflAx+QdIYdhsQs7DZZWMDmCN497/nTd//tI49cP7qMbE' +
  'rD8/ThAkOKzmN1Q6eRdSHL6E6O5yVMHn/8HJQPfAD5nN0vq23DsO3D0Drv3Z9897vedfex8x/5j48oX/P6bpgqt3PgnEoKnlI1/1PG0Glk/dOJ' +
  'cIJwPBWff/3Xfz0+Pv6qV70Kq/l+FeQf/uEfXvGKV/0TNM/jXbn02roucO5FWxfaG2h0bhpaeSKd143e98CJT2fOr03UDh4c8/3atHkGjQxJJ4' +
  'dz289fffUll3A23why+bnnnvvrTN6J8qoHmOzevftzu6+66ppfOB9kL1TR7h3tS3Q8N2E1/OnDxW35zkbfecLTWfeoh0Ft6tG2eQaNDKs7BZ9f' +
  'QMdT0nkuynkgP37BBRc8cMGbUK566VVXXYVwgu5kdO4dgM7NQyrP2DwyRucbT3g6sxQXTLSgBVPNPINGhrZsOZ48bCvovPzyy0M8L0BhbO7efc' +
  '1VGp39687R64ZzPQWdmyN0bhq975wTns4FpJOUy5RmzSNoZDg6r7wySWc6nkjn7muuuYbjyensj829o0OGbeN0bsa47eh9Hz7R6axQnJYeVKln' +
  '7FojQ9JZZ3TqcSFF5xt1Ot8n8Nz9ppBOjueOIejcNPg8z9DvZICOjl6/80Snc5KWcUKdS6vGrjUyJJ17rtyjPE+e8+ypPJHOCJ57+6NzdNPKtG' +
  'eoOxmcm3Z8/QSns0NpuQxFyC4xdq2R1aATlKeg85wYne/TPM9hlOfo0Mrz9JR5nnsfqZ/gdM5SKibuLJjnz8gK6dwZ0nn140p5hnSeF6NTw3Oo' +
  'sNCw8zxHeWTo7hOdTt5V1LJcYkogjAxP554rd8bwfDxNeZ6XEhdaY+W5mVu2o6M7drzpBKdz3oNWaOB3zprH70USe53QeaXueV5y9SUx2zZFee' +
  'ph2+HwHNa0vW7zdYzPC05wOtui2a+xaw2dK6GzzvC8cqeG59U6nef2TqqsWHkOV5Iwet95mROWTljmZZp6jE0oFPINJUZWg86dUnleEg/bLud5' +
  '3jdsQUIanZuXp3PHjnNPXDph0J6ebBUKjUK7YOK1RoOvzLKN0AnK8xI9bHt5pJ4Pc5668jx/WOU50DzsqG173eiOj5zIdC6nWU/eA9rHz3601+' +
  'cNsVdGJ+jOeGCot/LcPXTYNoZnykzsT7D/LW/a7jh2yclKp5SOn/NnstnxrJCZCb+z+k+vfdI8zbHd2scf3QH3WZv2/UpWCbt3s7XVcVt6VvJp' +
  '2nOZnGeIp0bn+QOYthE8uyjPT/Thee44tm1t6HwSuyfxrma6keqL1ymlXqKKtlEtl+EdSoOA/ZiM3+ZWwSMebMt3wfcfsNfo1AG9rCjL9k1xR+' +
  'xT/KAeXU7CRQAqcALh6XvhCbA/xI74V9BFfjy2NEuLnR6cIYoX6bregNZS7Guwr8Tej/Y5L3pUHAC2j0TyJsIjOtRrZjKTfAfgscOcniJ7x4Nv' +
  'gBKZglej4eUnZATqsjwiLhThZZOzcueJC8S/w7h+F2FPVf3kxqqefN2Tt4JolweaD8A9I97U3ESXRycPH1drZ/aaCNEvncrzVAVDl6cUDO0e3r' +
  'SNuJ6JdRt62LlROkeP7VwbOnGtGBTiZSP7Eq+yB8iL0WlT4mKRkIsdCym14+eB60O5+AlXNgKWd7Hta3TCk+tQahEHHpIxTzYN7i5eOBY0KB5I' +
  'nj9VjxHsx1lmV14hdtK4DW7FHu9I4XAV9u7gV3HjJcXjlF8l/v3mM5Gxh9IyPOIuHM6HAYDthL3EfgJiM7BRAHwwEqIj4ATAqHbM9jrJ/4JpB0' +
  '6L793p8g1hl67YH/tS6uVIRZf2hqQTlgXCNnf803Ax3KoLWNNGav6g8RU2tKhzIHRmJXReGTNtr+5aMCTDtkOZtlE6N+k4vuxtmmx+G77xiU8k' +
  'qm03o+7cs1Z0klTdWQsHURLXnRPsPVesQwzPrLcYfR/juViqoBZsg9vu4gJuAaENSfMMDSwidSx8Abaz9HWMtZNRdHYQTu2dQngC1CJ970cqzw' +
  'BP2kW14XUiX8dRq3RUY981R/V9NvS3Jtn5WZbFAD3ieJB3Koh1YUGXTsL5w9KwhA9zXuR09us6rGrDvkIzhH/NLNEvbnzVZ0mnfheXOpFHRb0u' +
  'dueirtT2CdcCi8HKtJoS+7Or2LMybCg7OTydEs9taWHb1KzKkEmVVNN282bG48suuODn/vAj/+t/feQj7L8//Lkfv0DQKgCOKM8dx+prQ6fXBU' +
  'KfP1pWGS5+7N404Gl1nfAeNpJPrIt1RLJNt1xbEf+hZFJpF3waKL6MByUDUDXBR25pOVPxnPETsOIL4Miji5dT7HEqnnemPTxdEYCKJtxMCEg7' +
  '7szRcDGPcnSfoDnh2WZDmIOXqICXpIwcwCenwL4oownihCcP0tboJAB2Cf+mZdiBojO2mKz4C6EKJJ3h8EXpfn3ECT0CHXbLtfRbZvF2zswISH' +
  'zvzDRzKizgt2wJ92FIOusxOjXl2XMi2cDKk31oc9g/k8G2Ywfb/ILzPrJt2556grd6fc+2c8694KrzGaCfOF1NJLsOVO4/rRGd8ibBuk5Ry1Yt' +
  'iUicGJ34Bq5savHlFL3o+z4VS6CK7S35cHNlyhwt8exnxeqo8CrFZyZVH7iIHj7/ZQs1JD4qc9DTlLgB4VY028W0phmsBJ86nAndaQM8zD4rW9' +
  'yca0cuEdiiZcDKSThhDUkJ+7pl/QGtKX0L33uC686yfAmOPs/Ou1qWZ1aLuA78S6FDDld/RDMpQt2pFt6S46C8XJZwU8ZoeAXY3g7qt0i8Iemk' +
  '4d7EQtJl/pXRtgnIlJ344gGMBDDcYNFYuTwxHJ0Cz53RgqHuyvNNAs9IXGhvH7NURrEIDxaw3gRNT86/6oKPfPjrX6/vqfc8tW2Pv+9tOzajEt' +
  '286XQG9eh1Ox5YMzr5TWI3giTp5PfLORAdNIV1xm+5w371/Ljfyd+HByAAY9bh/ATcEi7LYTYrvENJZ42qJcY1OAP1A5QHcoNPCjp1+ChyfzFQ' +
  'OnzMc0gCT1j20SLqMY7TaXOvN+BPrUfruk6F3ZWrTAcmC6OmKY5COPxYVOs4OeFowwJ+4QKaufyqAmJ1OcDhGWmBqOfKwvtjXDiILbdsuasp6K' +
  'SWI26BS/hO2NhFlH+fhYs0RiPXMnS1fW2NgxidWGISgBtiUXVMdoz4HN6qK1GGT8BspdYK6EwkVS45p5fn+aaE8kzTnqo5/F7sOc3w3Dy6Fz98' +
  'bPe5TF9m6v1RVt/2xt1Mhaq2JzsG7yq0Qt3Jrm42rv+kXovSud8jgj58LODXRgqd6GKxexdUxdrhzKcM+BvUG9Pp1HWnG7HSlMvKIcaXWwoLEn' +
  'CVBXtxAKxq+BZfFjmym8AiUoknfESUfbBRGQYCZtoqRfAxRITgbDlnPnkFq4F4SEF5agbxnFwZi0hrNE5nZsGRupV9RDufbNnlWJTZodvch7UE' +
  'KVacTmVfqN/wcim/U7sE3nwfdMIOHD4gMlJxv3DWjm4Yw6DliV1YGAKEb0CHpFNXnju7ep7nxZRnP2HbsFHfXrE80Y4d1+/Y/Ycf/vqAyq++Z+' +
  'dHXgbr218HdJ7/xjW0bOUK39mkdZpGZ1uM+A6YNS7eHZpKp8sfmgAfeKJi765yceN0+qgOE3Yt+FEkoQD2VSkYXq4l4IcHTViHY0R/cPWlV3X/' +
  'NeFJ1cGCLfPAUKhnqlQufc5dwDTTVp5mWVPIU+Hwxg3bJJ2z4i+kc0HfpcVVErNoHJxk0Agsta84na74NxyLYMA8EI8KwW1aqCfoTFi2VdeR8W' +
  'J5B/mPqIWU5fY0EdFd+MObWCU6NeXZvZxvd0hnr5zn9aPaGzseOXbeh/fUh1rLqb7nwxecD4uZnb5piJ5fK9Gdy9CZjUVPtMcgwPiQV0uzbBEc' +
  '9oEq5CWZDuX3Gh48b07RSSN00ljMVh3JU+ErqTvbAcUj4GCPjrMlp8uMhZ929BCk63IbGI3GQvJizKFyqqInK03bGrq8Dj6IqY/fBMUTQKVMq7' +
  'p37krL3Crbgk4rMsbU+Ap3nKvQloYZBq7UunzEaQWkK50CkJDCI2AXH4iFZvFOqNxYDzrZB6kHE5CcgKpUGMaZI5Zrm0f++D11uHHdGJJOjmec' +
  'zquXNW37yXkq6/b66+9+4PFt9ZWsslbf+Yfn7wDrdtuLbNmOdaUz6xFLmXIWAuo4s6l+J3xoKruYrdWyM20GKNpJuG0rlc6cR8PiAaUOUJnxvy' +
  'H53g7dwbII+kvPWbqFvkcJTY34OuGeUnoh1eQ4RcLsaZb7vHAaTmr7pDoVJnzIkrT85DEDrlILmv7miC0oP1uLabE9WoS76oz3BcmCZaXTacHw' +
  'KLKuIoITsWx1e0H1mOlBJ3u5kZ0YGzs4lm3whqjypIOafqkcoqIPwsfpOl2pPzr78zxTw7ZJ5amYFP888rlf37by5Q/rmT3n7N5x3YtPp35Xs7' +
  'FBU+QdpqQB60TvS+h3ugHJ2kL4/Q+4mgnpLEd0p+fRGJ2obFNqhbLgdlYhpE8KImLEzqMm00FerDYIR4rA8wL1einlauzjFqqmo+12GLr25lMv' +
  'YUvafoBYJRPNFmG4N5joQuesbiKoqzwRWCK8Y5HyrLjoVjc6MRcWSrPZxH/9OJ1uFdTi3PK6M6Bj8p51FjC8ICpK9Jm8WRHoZ28XHHFiTrd5+B' +
  'v6MBujFQnLeJ682jYWttXittdriwVez/763Lk7V21l0j0/97bz145Oi9I0OkOziUbeqHsiUErI4hTXK6A8O2l0QmhU0cnwDAQmDsmm0hnL2+i+' +
  'ZsJJbGPqHJ6bxxZFAsAVkcqu+1m2sWfdU6rCFScUSIXvkC6qYR4t7ICr1/2aOyo4d2W2RKdzMqyqElfKaekunXT6hEZtBV11ZzxXaqdbQFy/yS' +
  'ekp2VLfXXP7AXK7aQgdgGmeBSM/ageUB6IM7sCOhMVCWKuSjyp8j6NziieCs37RsPFVa5/5KWXX7mq5cv1nX+XWTs6VVIyqjuddN05H1qJB/dJ' +
  'XejErWIZs7VC3WnPy+SJK0veoBqtHzpTylCQI37uczypARElZ6q7dRCvhkqV/SLiBbY0Krx5j48BbAQiXYIedf51ucGvHuAF7fyFRZykM0NCOs' +
  'Mr0BIlSxANW5CbdtOdyaBcyp1QCjoQW/vMk+6Lzlog8mJuOMqIZBDqTuLug0xUmcfmFoalM5Hz3LZce77duyOBIT2rIhUnI/ORqz7y9eOznvfa' +
  '0knihZhOWI6Qjdtx/L522CBf5aVokWxYmO8EbabfaLzHEJ3ILK87aU86w0HCm+hQjApBGsKrr4zOugdJDqw3pbNhgCbo8ejBJQkEZGyrunx8NZ' +
  '21vyudDd1CkM++51oqVLp/WTqh0q7bmfnU0ukEbcwHHd/rU3fabR704j8m9GQuHJndvcU6oUrZ14ams9612vaNaYGhB2LF8KqHiRYFOvbA1Xsy' +
  'J4ysKp1UC5lmI4pCypRd83hCBYbvTmLEhoCqG4R0zoQB2XZ6rVD0zJx4Aj6Sx1Cq3evYS+ih4eMxszI6uecpoqXwdQMemgziJe5R07YsAt/sGO' +
  'IOHAxtZBXRTqFz2nMS2chaGAFyJQ/d6SS9Eo06nRa/I0Ebxo+csKbT6RzT6MzKNDF4pLPh5XfE9/Nq9gK7r0FqVVn/dKbmPNNr4bnyfCCFThkE' +
  'Arfzkd2P76lnMuuETit6ace8dDonwsLchm170lKNzFAQdDoWPA1ZfRTGkgT2QHT0nBk/UNKy7UWnHWqcqm1Phi5ew14ZnXXtIZ2GeSQ8ZVD2uq' +
  'tOKGe3iHha5SEOyKcXPLOMopPE6LSrIZ2BSEhUxADhQnInsyydhDheLzqtaMUfP0OhO1PoJDE6c2UR27K0bFamSkQhCqG23aAQcEIrqL1COvua' +
  '5xmjM6Y8uda8ZE/mBJOV0AnjdD8x24a8q8wvs+0pnjeBl9op3k6VPWEHhFm7yOAMXA7JTKZvOkk6ndog0WLju8znOSRYoe7MNKgqZWC0TAYqVT' +
  'jffZu2qkdUp1ogIZ37k3QqW72RdE9n5UwRtxq04nQmaoWwnmeqEMpUi0k7xbJ1eTCPVjuY7+mTzrpWjKFGqGlP5VALaBSJvG4X07YfOhPKc5mJ' +
  'ZEinFhgCNO9+BLTmsXd++MTSmqtBJ7vtWmC+kU6nXeV3FW5rjY2aokbGshxST1YjBFZV5C89rA+oQumCViTX1I6eFhWykgWiMnoTToBiytnnlW' +
  'dYFT/Ry3/tg84OPo04u4RkbI+riHLvpWJmxIRW9MGFclG6kwS5HnRO6JOE+CUEG4OTVA4mEnSSpO6ED7sqkwt1BB5N1JQIVwOM0DnIFrt90mkH' +
  'KrtD1DSUOZl2cugsu/zUVfG+mRXSeaVu2l7doxZe4cnphNkm5999992fO3fniYjmyvOdFqzDSYR6I+l0TotkvYMmjT0vihKIpUc0OZ0u6k5ejo' +
  'ZlsAHPvxTCFh7L0KkeyGRUaEmV/EEIoy70bKAbXyl09rWkRMMResD1OjN4HIZ9QOd7EZ2I7dRISKf6Zml0dnQqePYkEPXDujPeg04aiImZUAUv' +
  'iutogk5H1o7wKufpHrrTiUSFbFEaAWE31X6ireZ10nn4CHGPOBTtr8LQdKZNVemC5/tiYVtu2x47tvsj2zInrKyMTj2yR4mTTudcWcX6CmCvOp' +
  'BsR52hVcKrOlvcl5iSJGIr7P6Fz3lTuUUD0jmtmavwBFUdR5Y6VFdKZ50/i1C4N9sQ3yRIf+oymhvmyiwwfr0J7QLu60VnpkXDSrusJMoSzny7' +
  'HzrlzbLKfMgqw/TOZL7TFdWB2JhhjCtSkq47I3QWSICFSOWymlvU8VQOmHYgokCOwERVzKfWV0SnrOcDPm+9OrLabkJ5KtMWAP3c7neeeK7mqt' +
  'HZU8KHusonIsNk/lkcWLV7mogKiSdANhawRAUMXRhT9TRhxW4yZmuF40acjf2i+p7trgqn0dJOY2KFdKoZmw5Y4hYHxeu9ylqWj0B4KPQyx0WZ' +
  'APu/N53pHhXijSYkPQXFCQ+5BJW0TZO1Qo6AkxJVGhnPdzpT1bKssyDexMHQM1gmo2IXynwuL9AZaIZtEA6ODTVdkNKJoemEOhy9mo/J1Zrj+U' +
  'Y9bMu0524F6Oc+98AbT1R7dtXptLrTCRMwxQwlbxqxcNVTGdaJahkVWUbtqppw3GB+IDqdBJ1tlQ8M9vMyJCe9e8gwdHY80Po4kjjcVAxoq/cm' +
  'NTw+9wfa/AR5dbBWTt+Fzrqa5s68ABwcymomV5im6kWnKwxbLPridDpOIipUWAQTmJfj0urz5a50WjG/syDmz1plS+rOtqx3dIMGfIRZCg4aUO' +
  'W0iXkD0JlR2hPY/LCW8zwn0gDsggve9z6E84HdD7zznJ0nOpirSKfVg84s+qVlfBzApLH3pzXV0epsXTU7EwtOROseR4ywWc2gHoTOjiecTOg1' +
  'Baeh9Z5LmLYD05mZC2QpvKiJ96Id81JkwYnGdiifvgOlvyHYqXRm2mWVyycQP1oIxAQCV0vi9NSdjpiRwBU+2PcOUX6notOeVGknZqgH3em04p' +
  'atmAFTlvYRZpCYv2vJhFmNrwvAh+MV0Sn1J18N+8MfVtW2oDu1iWTnPfDSBx544KXnPr5tz0mB5vB0xnDUPFAr/lC3eWwUHBw0adio6WqJx1jM' +
  'Vk2cD3scwNwR0ClBR9BJhqGTDxJcIT/HQxdaF6vaSunsiOla3P9000JNcZnV6PR5wgIM73Jk1lk6nTNledld6I/QCQtvvNl+6ESLMgjnmlvYzk' +
  'XSqab7FWw+Jx2vXDVQV35ZOquuiHCpsoeK3JoROcEvv8cn48N/0yukEwDlyhN15+Mo5zweup7nnfdOJpdfffKAuaKMSrzDR7yPlHqo60J1suep' +
  '3OCTGLTecdSPR4VE+0lER5t7DRH/yZXQyecWYvaUikdoKTyR2ZXSmdknMo6qmHE51ZmpaXMts9wokF1EMjpiVpLODlXbevtlbyWck6aNM93ptI' +
  'RNG7bqQqszSiezZwvgrcvpJoE+q2wZOqnog2GpGPKk6IDmVl1x+dU0HTd1kueGgR/lOmhQYd0K1/NyNG1//dzLz7lk286TC8xVoDMMn3alc55y' +
  'J4eWA7Lv4Jifqx0MdadDZxN0qiTqYnZf1YNScpeUcfI9PnlZTWMPQGdN+bAOeazm16ZrtYL2wFVXTGdH1Bw6vIOS11p+k2qEnpaMJll6XX7BSq' +
  'OTjTXQbExm+2fUTdCn5fWgEzgJVONTMRJ66okQ+Wmg09aaevVv2VIie0RZZEmO0ZbMmR0cm56uHeRdGvljUF0NOgWj9TqD1L+VydW3Mn16686T' +
  'D8oVW7ZaozoabTAZo3NSmDPloEoCh8BkTL3ViOyqGEYK2We1KniPAVoF5/MIc32yw9O5iGnUgM9uC7R+8GKYqK2UzkyDBlVRW9qX6sT6XG10WH' +
  'BkUkTv9duFzqxougZetI3XWCC1vx86UeemnBDeizEJOtKZyUJKC3sOirKtPqJCkUlokzzKbKnp93yqbCBxB5Wf8gxuyBhZcVQotp5Bgk6bqpqu' +
  'Mk9RB6JxGzeXVFsfGrbZ0OisQwNamWOxCsPT2RIxCj41JN5CyIm15hqGTlSesiUCmepjiwm9HsGWyfpIP5JudPLWmtjoi0xkMMyLCWS97KknnZ' +
  '527WSphy3ptIQL3eIRKGH5uvFMWNcq+AqfRKtZrQ3ZC9WyyqIHBQ/M8z5gXtbQeRzo9BYKk0wK/GegxYeyempORQpFUKKsHMpgJh6zjczvhNhN' +
  'gHcUzKBqNAU+CJ3Eiaj5OJ2Q07BXRmdmTiuw8/q6qNRTXuX8hJy26UZq57vQiQFfPsPGOYC5mTInItMfncvM7xQTo1siI6Ylt1LpjFfyqVQyc0' +
  'o4eDSsyLcSGbjU1miGzhXTCUaoMokyL6RkVPbT2I2NRnbVJM8u8zttO0CTjdHpWpzOoXRn3oMdlLuVTjhOtBR7KDpnIw9rnzUM0qmby8peZBbZ' +
  '3wedsyJNxS7ZFIyAAc+xNPqiE/zBrnQeVMa5SOw0AjfOZ7KSz6uF9o6+YgevyZgIu77JIHFEAtIxdB4HyzY5gyxaPF4lUZsoRqcls+eR+Z0HtM' +
  'lI6KGUscTPCoams4HnUO5e2hSdTjIUnVl9f31d1AlPhnZIuwBgOjg41fqgE7ocCjqdOYp5GPalIw0Ae9HZY37nmGiooraqkbBdfF+6sxFozcuq' +
  '3CfvTaeTLEk2dK6YTsfrNoNM0DkdvauJDAxzPCd0OuPzO+1xKiaDygLv4eikqg6pm7RWgU4n2bNguStZFp4wqcpSpiAys6UbnVCQgNPfoHiwzL' +
  'OsUY+1Z0alh+6sUe48l1UxZNYLa27T6XRw9pHsNqM9H46H2nyBaPP+Um9D29C5mnSKJpJddKecFpmF5uDVQFsfh0bpLIuCt7T5nbbd4f0XsThW' +
  'lJVnyRCVfBNVmMNRtrTzixUiOmSV6BTH6G+J2ZbKVsgSgXiH1650NiiRHe156NO14pv20p0W0aZ3Flot/hNGymkql0SRl9BeIKoYs5tlSw/Ke7' +
  'ZfNGqzePAJdokzQ3mNRjqdTmQBN0PnKtEZ6k47ojslnQs85xXSWY7oTggH8pU8o/M72214YKqUeqoYAfKIDUmnNSCds156uaGUsupQuVI6ZafM' +
  '/uicoBJJsTgie4zL033ROR1Yovu7o5oZRr7DMn5ngNPIaJnq3neWj7HYBbtsqUvILHDa2+8kAae8MOlRvWcgz79m+RIYTlc63dipGzpXlu/kt9' +
  'Vx4patZVGNzhyNRfti1QtAJ78vsfmdfBllrJkWk4MdRm12WDoX0K7tbtqW9eaTq0FnP+nODPaItpThjnDGg6ld6cxwk5ivBeWIaG+nPzp5u0B9' +
  'Vi5mwvjdrGHFhhWuKwi7olHTNqXbdDlwRL18EN5jh6/DtCCodEh0BSUd1Jahc/XoLJcxfRl5dg+GQ6OgMytW5dRzo1qclN+glm7ZumoRXtUuvE' +
  'x5gVuZ1PqlsxydQVaXy4TJs4iv70nZo0VWiU5rADqxDXeZF1NhZJrhGV0YSFTyWUk651Q/GNH9J4g5b2l0anrSiWR9+XlnxV0UCzSpS9gJaGRV' +
  'JEWnpa/5JnrLW1VL7RDPqA6DTpnTqfs4Wr22lZjkeVLQaZ+AdHqOpDPa9QvLPWG6PWhM0TvSDfPVkeSDEy7jQRWdYsmS+FrKhPss3oIY/3Gohu' +
  'OndMyEEyO4Gq1GZ5ZiCwA+6zJckLJeo2XeXINCiOVgkk4rNv70ppO3a+Xzmfukc4avwit7FIBETbwWElDGacwjMatYTKSmfElirfeSTifej8T6' +
  'nSk5Lrn49Rj6jex8yuElVF2/E3Sm2KlWqDl5cGzGU1QG+lzOOoWlf+E+Ap0VoztXhU7xEIL5GLVs5drXZQzm2naGupiVw0VfJyMci5HbdRw+1W' +
  'qahnM8YkvT45LYUAV/qzb+48KTJHlm/HXYkUZnm8qiYCcS1rRxpWnmgiFR+8KqGRoWEdNB6HQsPmw5pM+LWveoI2dyWXwucvQDBU81xou3KcKF' +
  'lPiNwIB2QKORlQIV1DE65SoXpFwup0ZlLKyLb2bkKkdR3cnX7nVdeU14rABXx+HLWMe8BmzHFxDvBTFM0LIcfSKzgd5Py7JGgZYba06nba9DOu' +
  '1w2nLU7wyz0OyaL6JmIGGb9GxkF8JsxRsGtpxPg4AvyKB7I5ay21zCY/M4E0yZWCnjhuxVpfmRNT2vGVkuvYBPlSPW603qTmcwOsPr0vdFbXvS' +
  'AySqqV80qosXyrWSfcwaJNoUOr4GUyG8T95yulOoxBkeFQocJ95eYuIrXjWuOw84crWF6Eqg2AoTAvUTOBLaevSnGo07qwmm2mTC4ei0DZ3y2U' +
  'UHA3/E6HQc7nzwBVYmmUJ0+aBJIys52m0VpnTdMtwX7IzDK2BdLRAiQprlcKJ2lmKMyMEoRvzM4GVRLqjpzgPirHCKf2Su2KJayhLermm2u1xg' +
  'exA6SXhdvFqfG83AEmqu8NggOTJvRx6bAp/PjcNWrHZ3viq2cjgddDb6tE3K2+HIENkBjHwTvHgR4beMBwsgLya+vj4cjGCbBAuabboODYcjhM' +
  'uNLtfLEA3o0pK4BtOOq84jOvjMi5su+vMby3Y16Ay0+ZkRv9PTgqDsjc6SUoQBjVpsMyISouY+16hehxsrhw2qwcJERqdzGd0JnyhE9I9c0dOL' +
  'OIQ1uVAwIKqtt6NXsfRPJw2/f+D3uREzbcOFQ2EGTyeqCAqSWzFlJP0+OPjVYiNCWzufyf50Z5YnJ5FOJ0pnzfMSfqe4VbLPDF97DGezVKvhdW' +
  'tpreujCHZkv04Qr3FC0XlcFKu9FrqTgrcIDWfpUnR1Xeo5/K0yWLYTePEhaUm9aEjDrlG+6ibeWZjPX2NuUxAQsQZlpMYOHq7wpjbDgyT7mXsO' +
  '5W+zB2UkDD54jtiCxkODVXyCPfjpaJYhHgGE0gHoXOKLFbKNKe2XzszCkgfXU55eO3YXW9gEDPFLNCpqEHk8nK++FHt7hDcFxn1zOmfxIF5ikW' +
  '+xyKLn8agQ3Ba8a4XE0WJRIVxUUVvH2OMDcTTSjXcZbwylMdd4ARWyxwf6hfoK6PzVX60Y3cnviib6U9jR32ADuR/+NZP1u+8jC+w1szP7JwuT' +
  'bbiH4bw0jxYas5Hx1tc37HVmE2mvjsc6G+ez2dlZ/tastrtu37CnRM6s0/dWs3hoeX5xi3he22e+1wGz2fjjmU9cjNgGSfGjdzFqa062JqXwkc' +
  '9vtQuttlo/1YP/2I92I1vrequjpzgx0/W9wejMpvYmOj66zz6x6TzeUpv2hRjP48WzqgaSjj89NsZuWK62WkcajM4l+sLKL03cmLVXdP1WwzQ+' +
  'EelcZ0+ukZXTOcbUft7HldBgHBhj4/ZYtpmtjLGXcrnpTG66Pu1nOjk/O3uwxl6r1bj6rh2Ep7szxuwAXPtiOqdG/OnaTHamxq3pXHYePmf7gg' +
  'Xfr43lMEIxDSoiN93psGekVqs0Z6bxI7VbYUO/VgMbqebDR2s1PEJtTBzBvsyfYKfo2/hBtsfamKHT0LkO6RwT5vM4zlh3SOB9rCaqEOfsBhVz' +
  'l8ayzPFlPvxCLfMZkRxuQ4eWDoWYmZfHWlMVtKcQDfGgTfIEgazzwzWYUcXNa+q1GtgYYI/nLUDVBIaspiBAQQnb/bgH1HSog9nAlgclJDNPQh' +
  'hknqg1f3IYMfCgIgPjGp6XNXQaWY90knahSiEsTbFGuJqtuaQ6CY0Wa230OZFOh30sgCUHJkUIbTKgYmEYj9Yz9mzgqHJHBkxhASKLNYbQ1Mcd' +
  'h8AiIlkRFfzV/+TQOVh50ZnNzLOtIE/7ip8ihQL2KJunUG4CKwJBlBGC0nZmtkrZKM9+l9G7aZcssD+PMDwhLsoGhoqh08j6o9On9GO2PQdTor' +
  '5C+exf3yEztr3oOAdamPeeCcjBLKXPQTeNFqOTx5snGblMt+7P1DM1VKVVFbX3YFWfOeLU9+OE4n0OnZmmQndCUT6hSzbUQdcy7WoVaxJbxING' +
  'q0xVz3rQmqZKbkEdWnB+iu0hi62aiLMgC0yfIw7b7/4yaTDdCQ3Ojd9pZH3qTujfvwjpdUrncsyJs32Gqm2POWQW6LQzTaY7ZwKasyeq3oQ9GQ' +
  'g6LS/zfrVAa42SGSrtSwp0NkjBLnnQYbdG6P7nJJ1B0MrMAccL3mN2x3NeoGQOLFvCPjhJqX0AyqE77EcAhjIs2BrUsmBg5ylZpJRXbD/nAp12' +
  'QFo2Gx+ma7ncwJEiQ6eRk4BOj8xNHyxQtGxd5m96ds6BZ5/pvmyBgEk5QxzmdzqQXN1n21+jU4JOkqHOlAgszBJqv1+WXEF6PaBuB3GzYU32wv' +
  'PK72S6c7pMD4x5dL89QUhnEqZgtAKnBvp50j7gMN2ZJ1bnM9DJ4jO0GpB9SGeDVhmKc5xO3r6OMuMayjOCgBrdaWQd0lnzMAcOwResYgmoPU2c' +
  'dgHbjU16PCrE6ISiB6hx0ixbh23RznC7copM2Q1ZT03FQom1Sb44AHEmD8pZHbgJpfvmYTXDEUZcljLTFtuTs7c6THcyOksBvE5rmclyYdEJPg' +
  '6QV+kcLCKDO3meBEAn8ZYyfEa6Z+g0si4tWw/W1ZhCVcT72hzkZWbMspzkMVuH+Flc5W7KqXY4nXamxOhsUVhd6zJY0BirpERwBleTZX5rdtJx' +
  '6jbYr/t9Wc1JmGULswz2eW0oN4SBAbBjKpXZsItss4DWbMS7GuzPFNieqtj3e5oGVTaQBNOgrGsO6M4Os2wZndmh0gKGTiMnAZ3Em7GXCKkuMi' +
  'YEnR7dN3sA8pVMf83bdssjnSw2H2MqbrpE22PT0zlwCYEyWBJymvmtvKRwRPidk7b9AiGtLCEN2x5xSD7HDOiDkOEMoPSxwhfJmwC17Xl0wW5R' +
  'z57wKG2Aj3lwEdcQp7RtF7wCDBaE1hvQ54y6ZD828vEgFtQg3lxmgHpQQ6eRk4zOgx5zCDHDCROkoGRwqqaeeB+bqlJStWdgje4qo8me/ClsJT' +
  'bbYuYkrCblMLwmFqp0ogYV3hi1ZXtZgMkFWWbCEojKks7/yevC2UGQ4IBAvXQjoPNjtTYzYUFJQ3aVFg4Q+sKs47xwsLbAXi/AJIMG2x+0R6v5' +
  'Y7KhAEz6o1g/DAXK7Awahk4j69DvxEgrQ+HJzJMezoWZqoXzo2YoLKJV7QCd5XJQXpqwW3zeywGsRhjjRnCWPsm8SWhmiM1zn6RY2NDCuVTwgZ' +
  'r9HHLuAZ2QFW2UATO69H72+zgbDMDBrYOqLmQ9D6Y3QaCJ0sWCV8pAMSFlp7kP3Vua484yqF0o7meMOl5fK18ZOo2cbHRmRMm1n8vk/LGxF8bG' +
  'avB7+BTDC5lMrjbh+z78Vpseq8GLdV6bx7YZ28N2ApvU5b6mc74/LQr++PZQcVeDMsHpHKjX+sHpDpbx8TOo1cSWuRxkR/iBsOhvDPbb8XOdGl' +
  'QWst/E56ZzTPjx4XxqNUOnkXVI5/EU+8TdoaHTyClOJyfKXkWy7G7HsA2dRk5dOu3h6bSPjyKNHMLUChkxuvOEMHCNZWvE0LmOxdBpxNBp6DRi' +
  'xNBp6DRi6DR0GjFi6DR0GjF0GjqNGDF0GjqNGFkJncvUDhy/BYzs1XjZ0Glk/dBZG5mcLLRa4STJz0y2WyMj45n8ZGOyxd4qFKBFfaPVHqllMh' +
  'PtxmcmPzMvP5tnG0/C9JCJBtsL72XPNxiZyGTGR9ojrRa2uWf/tFuFdimXyZTYzibVWh+5RmFkpACrXTS/VmiNtNmW7OOfaTcKLXgxOzJZKBTS' +
  'Gu41vsZ2027NGjqNrGPdie0JHLXQTQ3XZvFmM1kPZm5SEqjVPXxYVzRgvwRyWZYs9CGCriGz4bLnVC3QPsJXjQn4MjCe2IVHA+o9KQ/nB7AUFU' +
  'zabJfL2PsSdkkJ+x1enOy23k4tgCYr/EOGTiPrlc4RRh9xSAgcLJROO2JVNQpLSDoutJeFmZXZKnTxqcoFFbMMJ1c0pLbCdQxhdbxsxp4s43xR' +
  'ufBTuYyTM2kVMFWQeHLFu4K2NpRriRXdW7CqV9oa6bASdECGaWRr6DRy8tA5jUs5Erm84ySDyyEL+PwHDM2A4yXoPACrA7M/RE/2A7jaMsASlC' +
  '3XFatQ4sLAWVzlFLd1YGHvAJbyFrqT6csQEka0GyCdluO4rlioVazGVvBIYAXZpLc5hcOBQ4L9hk4j65dOm8JK6WRO/LVUDixcDH0GtBbTeGCx' +
  '8mUWfWzPxzQrkV3fDwCJQneqNRHZBuxFQafHV6q0qtUqQxbpxM8oy5brWxgWxHq02KEIeqPAZ6YQ96TurHuuawVwKkuGTiPrl07oN1K2QFtilA' +
  'a1JaymnqUBdARqFVqt1tRUi0eFZvBtNwj4cpA/7QjSsrQMi6gXCoURiDIVJkfykXUU2+x9WMk7g+002T4UnXAMBHyS7cHxFuBwrcl2i0eFCmgm' +
  'J+mcZ4xjwyKHThg6jaxfOhcJZeQQbjPOwKrpSFG2DGqtEHf3PDRmCV/Ll+nOoEylG0gL3Y5Yq5bRfAYeMEqkdOc0V9BIpyWWCNek4FipdLbZzs' +
  'pzSOd+Q6eR9UunTanFHEyugwqgq5x90lh1YsDN4JJfluUSXPIbgkGcTtisOtnlgPUqxn4czMRQotPpU/QxgU52Fk6Czi66ExdUn4ZAklc1dBpZ' +
  'v3TCekOMTp45rEKQhrygXMlCNOmfDQjz+Jh6dem0+AzSecAB3dmtMV4b47BkXyadTkfSybzbJJ0khc4JYJo+swghJW/a0Glk/dIJoZ6AO55juO' +
  '4ByUg6aZxOkfBghEK7ypBOXC6hkF6/04BQkisjSVE6x4iiE2K25IDQ5xqdJJnvHIGN2naHEqbFZw2dRtYvnXWCMdI60ueSgK+SC8xSSss0gPoB' +
  '+hU6w6Bh7zuuO8VYc+FvcDeF7rR4uFaKBtRiwBOhNocuRieN0hlQUf3gYePadDptNIdnbRvd2QVDp5H1SyfPWwQT8jc6L+kEi5epVch88uX/Ft' +
  '0j7FWuYYO6rXQnr0YIVK2QlqKcplidQGuiRDfN76TS7+Q1DS7sBDYQJQoROm2eonXItG23MM5bM3QaWb90zjt8XRNYwRawU/Yuwwr9UEtqsCxW' +
  'I2QaDvtcuRDSuRgEJCIKKGjsbhEaqMRHgk4S0skrjiye+ZxOpxNMZQDZq9v2DC27znCmraHTyMlBZwcJWbCxrs61GoJOiOQ6gKeDRQJIZ5Xx6s' +
  'EK1oDQxAEgGNCaJdXA1eCkkph6G3ZgaXmPuGVrqXwnr0YgjhgP/EyXmC0zaNmLC7Zt58pV5nguGDqNrF86IahaJry2llmVE5JOC4vlmEsKS4Vx' +
  '3UkZDYRXA1jlhVlJ5wzwguV+Mb9zykOns53pSqf8s4B6M9yD53fTnRN4ZnPQw3YJS3lrhk4j65dOqNqzyCKDwT3iCnLAlbTcRMwW6vHYLy2sai' +
  'eyKo+j3Ir5h5nMPgwtEX0mCUWI7YTfWUAVHc+oAPTxNMv+wGWWbeFANputMl/XcbJD0UkMnUZOBjo7FHTivgwFU7ah0WnFa4XgNWCpRoIq8RSd' +
  'M557Cwn0agSMAE1wfRqJ29CAuFqdLXWOuJx3J4XOSUi4xOlcIkqlu6ixC0NchIPUMXQaORnozLQp053VWlAO559kMdaaqOQrczoz+0nZwskkQn' +
  'eC/ToS22uNOC77gBcpheVIS16nobDP8aQ2joM4SZOWbYfyUBUjM8CIE+VlhYPSaXSnkZODzpkAan320zIlXqcvOjHX6Cg60b2M1QrVUbl6MeIA' +
  'x4DI9gr7GX4uzv0uAJ30QHQXDQprhUZ3AJswKC04PfgfKQ8zydPQaeRkobOOjicWH7QzGp26ZWsLOsEOhaRj1eWzOWW+0woKKYovIK1oJ6I2ak' +
  'uBBlQqMKwbnE6rTGJ08gnc+8ZwyVD2AyJFC5AQhbmnQCdEd8NzNlEhI+uQzkzbg2oCmGkyr1xM0FDYHYR+5StLvKFBFuc8c1InYXql6GGQhdxo' +
  'leqSqbDdQZODQHvxSVzq2j3CfMyFxkyjDY0YLOLNCzqtwKPY4eRJ+DECUSEgkeg1SB2KrzRmsouL2QMFtHKHMG0NnUZOGjrnwZHDXGNH0elw2z' +
  'HgbUcCyKQAnY6j/D8ig0Q8hFSWs68Jg8zOCgs0IEE4MxunxDDldwTGgrIVVEFjo0WMlm2VKUKYlUagfrDF6+cdnEQqdp3NzPBfpN/KfdDFgS+C' +
  'b+g0crLQWePl7U7Y/kvRCdqNZz6jdIpPWCqjwjMsluDQRtPYhfyoJSqAmJZkdEId3hG50wDoxBBRi6Bpq1xKAtNFC2WtXRE2E7PbAfyrqhv4DL' +
  'SGbeg0sm7pzFQJr5OdCQNAkgnAClIXHlbBw7/hNi57w+aWLbE4RqDnKNJJKYkJkGxPVwVwLoaVFri2bmlKksgSBqCTh3+4kAM1xDEMAzf4vuqD' +
  'XoQaHa4+14iRtadznAZ0ifl86jFvYitLqvpletDoZ+YrekO9aco+QXglH0aUiPbhepYGNCqyn1BntoocwqTQdlYcseU5RH0MZRICS9BxM9yDl5' +
  '2H+d9ao0zs1uB5A/cv8bFPkhEjJwOdmWG6q/u+X5vwh2kPX/Mr2Wx2frpjbocRI33Q2ZekgWjb5qIaMXK86LT7xuxFJ9EMBUaM7jxRxdBpxNC5' +
  'Gn7pEHtfHj5DpxFD54ulG80NMmLoNGLEiKHTiBEjhk4jRgydRowYMXQaMWLoNGLEiKHTiBEjhk4jRgydRowYMXQaMWLoNGLEiKHTiBEjmvxvwt' +
  'KpHK3GYakAAAAASUVORK5CYII=';
var PDF_BARRA = 'color:#1a237e;font-weight:bold;font-size:11px';
var PDF_REGLA = 'border-bottom:2px solid #1a237e';
var PDF_APAGADO = 'color:#8f4b00;font-weight:bold;font-size:11px';
var PDF_CABECERA = 'font-weight:bold;border-bottom:1.5px solid #666';
function _pdfTh(ancho, texto, alineado) {
  return '<th' + (ancho ? ' width="' + ancho + '"' : '') +
                 (alineado ? ' align="' + alineado + '"' : '') +
         ' bgcolor="#eef0f7" style="' + PDF_CABECERA + '">' + texto + '</th>';
}
var PDF_ANCHO_FOTO = 170;
var PDF_ALTO_GARMEL = 52;
var PDF_ALTO_MINHVI = 46;
function pdfDelInforme(p) {
  var html = (p.tipo === 'servicios') ? _pdfHtmlServicios(p)
           : (p.tipo === 'sha')       ? _pdfHtmlSha(p)
           : (p.tipo === 'urbanismo') ? _pdfHtmlUrbanismo(p)
           :                            _pdfHtml(p);
  return Utilities.newBlob(html, MimeType.HTML, p.numero + '.html')
                  .getAs(MimeType.PDF)
                  .setName(p.numero + '.pdf');
}
function _pdfHtml(p) {
  var d = p.datos || {};
  var fotos = _pdfFotosPorHito(p);
  var noInsp = {};
  (d.noInspeccionados || []).forEach(function (h) { noInsp[h] = true; });
  var cuerpo = '';
  var huboAlgunPct = false;
  var HS = _hitosDe(d);
  var av = null;
  try { av = _avancePonderado(p); } catch (eAv) { av = null; }
  for (var i = 0; i < HS.length; i++) {
    var h = HS[i];
    if ((d.partidas || {})[h.id] === undefined && !fotos[h.id]) continue;
    if (!(d.partidas || {})[h.id] && !noInsp[h.id]) continue;
    var trozo = _pdfHito(h, d, fotos[h.id] || [], !!noInsp[h.id], av);
    cuerpo += trozo.html;
    if (trozo.tuvoPct) huboAlgunPct = true;
  }
  return '<html><head><meta charset="utf-8"></head>' +
    '<body style="font-family:Arial,Helvetica,sans-serif;color:#000;font-size:10px">' +
      _pdfMembrete(p, d) +
      _pdfIdentificacion(p, d) +
      _pdfAvancePresupuesto(av, d, HS) +
      (huboAlgunPct ? '' : _pdfAvisoSinProyectada()) +
      cuerpo +
      _pdfObservacionesPorHito(d, HS, noInsp) +
      _pdfObservacionGeneral(d) +
      _pdfFirmas(p, d) +
      _pdfMinutas(p) +
    '</body></html>';
}
function _pdfMembrete(p, d, titulo) {
  titulo = titulo || 'INFORME DE GERENCIA T\u00c9CNICA DE INSPECCI\u00d3N';
  return '' +
    '<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:10px">' +
      '<tr>' +
        '<td width="130" valign="middle">' +
          '<img src="' + LOGO_GARMEL + '" height="' + PDF_ALTO_GARMEL + '">' +
        '</td>' +
        '<td valign="middle" align="center">' +
          '<div style="font-size:15px;font-weight:bold;color:#1a237e;line-height:1.2">' +
            titulo +
          '</div>' +
          '<div style="font-size:11px;font-family:monospace;font-weight:bold;margin-top:3px">' +
            _pdfEsc(p.numero) +
          '</div>' +
        '</td>' +
        '<td width="215" valign="middle" align="right">' +
          '<img src="' + LOGO_MINHVI + '" height="' + PDF_ALTO_MINHVI + '">' +
        '</td>' +
      '</tr>' +
    '</table>' +
    '<div style="border-bottom:2px solid #1a237e;margin-bottom:10px"></div>';
}
function _pdfIdentificacion(p, d) {
  var sector = (typeof _nombreDeSector === 'function')
    ? _nombreDeSector(p.sector) : (p.sector || '');
  var ambito = (d.ambito === 'torre') ? (d.vista === 'estructura' ? 'Estructura de la torre' : 'Torre completa') : 'Apartamento';
  var pares = [
    ['Fecha de inspecci\u00f3n', d.fecha],
    ['\u00c1mbito', ambito],
    ['Sector', sector],
    ['Torre', p.torre],
    ['Piso', d.piso],
    ['Apartamento', d.apto],
    ['Empresa ejecutora', d.empresa],
    ['Ingeniero(s) residente(s)', (d.residentes || []).join(' \u00b7 ')],
    ['Ingeniero(s) inspector(es)', (d.inspectores || []).join(' \u00b7 ')],
    ['Estatus de la obra', (d.estatus || []).join(' \u00b7 ')],
    ['Versi\u00f3n', _versionDelInforme(d)]   // r47: preliminar (campo) o definitiva (cerrada en oficina)
  ];
  if (d.copiadoDe && d.copiadoDe.nro) pares.push(['Mediciones a partir de', _copiadoDeTexto(d)]);
  if (d.lista === 'v2') pares.push(['Medici\u00f3n', 'Lista v2: estado, S\u00ed/No, piezas y puntos contados, cantidades']);
  else if (d.medicion === 'propuesta') pares.push(['Medici\u00f3n', 'S\u00ed/No y % por subpartida, escritos por el inspector']);
  if (d.formType === 'hitos') {
    pares.push(['Modo de llenado', 'Por hitos \u2014 avance declarado, no verificado']);
  }
  var filas = '';
  for (var i = 0; i < pares.length; i += 2) {
    filas +=
      '<tr>' +
        (pares[i + 1]
          ? _pdfCeldaEtiqueta(pares[i][0]) + _pdfCeldaValor(pares[i][1]) +
            _pdfCeldaEtiqueta(pares[i + 1][0]) + _pdfCeldaValor(pares[i + 1][1])
          : _pdfCeldaEtiqueta(pares[i][0]) + _pdfCeldaValor(pares[i][1], 3)) +
      '</tr>';
  }
  return '<table width="100%" border="1" cellpadding="4" cellspacing="0" ' +
              'style="border-collapse:collapse;border-color:#bbb;margin-bottom:12px">' +
           filas +
         '</table>';
}
function _pdfCeldaEtiqueta(t) {
  return '<td width="21%" bgcolor="#eef0f7" style="font-weight:bold">' + _pdfEsc(t) + '</td>';
}
function _pdfCeldaValor(v, columnas) {
  var t = _pdfEsc(v);
  return '<td' + (columnas ? ' colspan="' + columnas + '"' : ' width="29%"') + '>' +
         (t || '&nbsp;') + '</td>';
}
function _pdfHito(h, d, fotosDelHito, noInspeccionado, av) {
  var conPeso = !!(av && av.pesos && h.codigos);
  var filas = (d.partidas || {})[h.id];
  var extras = (d.partidas || {})[h.id + '_extra'] || [];
  var obs = (d.fotobs || {})[h.id] || '';
  var prom = noInspeccionado ? null : _pdfPromedioHito(filas, extras);
  var declarado = null;
  if (!noInspeccionado && d.hitoPct && d.hitoPct[h.id] !== undefined && String(d.hitoPct[h.id]).trim() !== '') {
    var vm = parseFloat(String(d.hitoPct[h.id]).replace(',', '.'));
    if (!isNaN(vm)) declarado = Math.min(100, Math.max(0, Math.floor(vm)));
  }
  if (declarado !== null) prom = declarado;
  var derecha = noInspeccionado
    ? 'NO INSPECCIONADO'
    : (prom === null ? '' : (declarado !== null ? 'Avance declarado: ' : (conPeso ? 'Promedio simple: ' : 'Avance: ')) + prom + ' %');
  var html =
    '<div style="page-break-inside:avoid">' +
    '<table width="100%" cellpadding="3" cellspacing="0" ' +
           'style="margin-top:12px;' + PDF_REGLA + '">' +
      '<tr>' +
        '<td style="' + PDF_BARRA + '">' + _pdfEsc(h.nombre) + '</td>' +
        '<td align="right" style="' + (noInspeccionado ? PDF_APAGADO : PDF_BARRA) + '">' +
          derecha + '</td>' +
      '</tr>' +
    '</table>';
  if (noInspeccionado) {
    html += '</div>' + _pdfObsHito(obs) + _pdfFotos(fotosDelHito);
    return { html: html, tuvoPct: false };
  }
  var cuerpo = '';
  var tuvoPct = false;
  var numVisible = 0;   // las visibles se renumeran seguidas
  if (_pdfEsLista(filas)) {
    for (var i = 0; i < filas.length; i++) {
      var r = filas[i] || {};
      if (r && r.fueraDeAmbito) continue;        // de otro \u00e1mbito: no se imprime
      var pct = _pdfPctFila(r);
      if (pct !== null) tuvoPct = true;
      cuerpo += _pdfFilaSubpartida(String(++numVisible), h.items[i] || '', r, pct, false,
                                   conPeso ? _pdfPeso(av.pesos[h.codigos[i]]) : null);
    }
  }
  for (var j = 0; j < extras.length; j++) {
    var e = extras[j] || {};
    var pe = _pdfPctFila(e);
    if (pe !== null) tuvoPct = true;
    cuerpo += _pdfFilaSubpartida('+', e.desc || '(sin descripci\u00f3n)', e, pe, true, conPeso ? '' : null);
  }
  if (!cuerpo) {
    cuerpo = '<tr><td colspan="' + (conPeso ? 8 : 7) + '" style="color:#666">Sin subpartidas registradas.</td></tr>';
  }
  html +=
    '<table width="100%" border="1" cellpadding="4" cellspacing="0" ' +
           'style="border-collapse:collapse;border-color:#bbb">' +
      '<tr>' +
        _pdfTh('4%', '#', '') +
        _pdfTh('', 'Subpartida', 'left') +
        _pdfTh('8%', 'Unidad', '') +
        _pdfTh('12%', 'Proyectada', 'right') +
        _pdfTh('12%', 'Ejecutada', 'right') +
        _pdfTh('9%', 'Avance', 'right') +
        (conPeso ? _pdfTh('8%', 'Peso', 'right') : '') +
        _pdfTh('9%', 'Evaluaci\u00f3n', '') +
      '</tr>' + cuerpo +
    '</table>';
  html += '</div>' + _pdfObsHito(obs) + _pdfFotos(fotosDelHito);
  return { html: html, tuvoPct: tuvoPct };
}
function _pdfFilaSubpartida(num, nombre, r, pct, esExtra, peso) {
  var marca = esExtra
    ? ' <span style="font-size:8px;color:#8f4b00">(agregada en campo)</span>'
    : '';
  return '<tr>' +
    '<td align="center">' + _pdfEsc(num) + '</td>' +
    '<td>' + _pdfEsc(nombre) + marca + '</td>' +
    '<td align="center">' + _pdfEsc(r.ud === 'estado' ? '%' : (r.ud || '')) + '</td>' +
    '<td align="right">' + _pdfEsc(r.pr || '') + '</td>' +
    '<td align="right">' + _pdfEsc(r.sn ? r.sn : (r.ej || '')) + '</td>' +   // S\u00ed / No va donde ir\u00eda la cantidad
    '<td align="right">' + (pct === null ? '' : pct + ' %') + '</td>' +
    (peso === null || peso === undefined ? '' : '<td align="right" style="color:#555">' + peso + '</td>') +
    '<td align="center">' + _pdfEsc(r.ev || '') + '</td>' +
  '</tr>';
}
function _pdfObservacionesPorHito(d, HS, noInsp) {
  var filas = '';
  (HS || []).forEach(function (h) {
    if (noInsp && noInsp[h.id]) return;
    var t = String(((d || {}).fotobs || {})[h.id] || '').trim();
    if (!t) return;
    filas += '<tr><td width="24%" bgcolor="#eef0f7" style="font-weight:bold">' + _pdfEsc(h.nombre) + '</td><td>' + _pdfTexto(t) + '</td></tr>';
  });
  if (!filas) return '';
  return '<table width="100%" border="1" cellpadding="4" cellspacing="0" style="border-collapse:collapse;border-color:#bbb;margin:10px 0">' +
    '<tr><td colspan="2" style="font-weight:bold;color:#1a237e;font-size:11px">OBSERVACIONES POR HITO</td></tr>' + filas + '</table>';
}
function _pdfObsHito(obs) {
  if (!String(obs || '').trim()) return '';
  return '<table width="100%" border="1" cellpadding="5" cellspacing="0" ' +
                'style="border-collapse:collapse;border-color:#bbb">' +
           '<tr>' +
             '<td width="14%" bgcolor="#eef0f7" style="font-weight:bold">Observaci\u00f3n</td>' +
             '<td>' + _pdfTexto(obs) + '</td>' +
           '</tr>' +
         '</table>';
}
function _pdfConPies(fotos, meta) {
  (fotos || []).forEach(function (f) {
    var m = (meta || [])[(f.num || 0) - 1];
    if (m && String(m.pie || '').trim()) f.pie = f.pie + ' \u2014 ' + String(m.pie).trim();
  });
  return fotos || [];
}
function _pdfFotos(fotos) {
  if (!fotos || !fotos.length) return '';
  var html = '';
  for (var i = 0; i < fotos.length; i += 3) {
    html += '<table width="100%" cellpadding="4" cellspacing="0" ' +
                   'style="margin-top:4px;page-break-inside:avoid"><tr>';
    for (var c = 0; c < 3; c++) {
      var f = fotos[i + c];
      html += '<td width="33%" align="center" valign="top">' +
        (f ? '<img src="' + f.dato + '" width="' + PDF_ANCHO_FOTO + '">' +
             '<div style="font-size:8px;color:#555;margin-top:2px">' + _pdfEsc(f.pie) + '</div>'
           : '&nbsp;') +
      '</td>';
    }
    html += '</tr></table>';
  }
  return html;
}
var PDF_ANCHO_MINUTA = 500;
function _pdfMinutas(p, sinSalto) {
  var fotos = (_pdfFotosPorHito(p)['minutas'] || []).slice().sort(function (a, b) { return a.num - b.num; });
  if (!fotos.length) return '';
  var meta = (p.datos || {}).fotosMinutas || [];
  var html = '<table width="100%" cellpadding="4" cellspacing="0" style="margin-top:14px' + (sinSalto ? '' : ';page-break-before:always') + '"><tr>' +
               '<td style="color:#1a237e;font-weight:bold;font-size:12px;border-bottom:2px solid #1a237e">ANEXO \u00b7 MINUTAS DE CAMPO (' + fotos.length + ')</td>' +
             '</tr></table>';
  fotos.forEach(function (f, k) {
    var pie = String(((meta[f.num - 1] || {}).pie) || '').trim();
    html += '<table width="100%" cellpadding="4" cellspacing="0" style="margin-top:8px;page-break-inside:avoid"><tr><td align="center">' +
              '<img src="' + f.dato + '" width="' + PDF_ANCHO_MINUTA + '">' +
              '<div style="font-size:9px;color:#555;margin-top:3px">Minuta ' + (k + 1) + ' de ' + fotos.length + (pie ? ' \u2014 ' + _pdfEsc(pie) : '') + '</div>' +
            '</td></tr></table>';
  });
  return html;
}
function _pdfObservacionGeneral(d, sinActividades) {
  var t = String(d.obs_general || '').trim();
  var s = String(d.obs_sp || '').trim();
  var a = sinActividades ? '' : String(d.actividades || '').trim();
  var org = (d.agentes || []).filter(function (x) { return String(x || '').trim(); });
  if (!a && !t && !s && !org.length) return '';
  var filas = '';
  if (a) filas += '<tr><td width="18%" bgcolor="#eef0f7" style="font-weight:bold">' +
                  'Actividades en ejecuci\u00f3n</td><td>' + _pdfTexto(a) + '</td></tr>';
  if (org.length) filas += '<tr><td width="18%" bgcolor="#eef0f7" style="font-weight:bold">' +
                  'Organismos presentes o notificados</td><td>' +
                  _pdfEsc(org.join(' \u00b7 ')) + '</td></tr>';
  if (s) filas += '<tr><td width="18%" bgcolor="#eef0f7" style="font-weight:bold">' +
                  'Servicios p\u00fablicos</td><td>' + _pdfTexto(s) + '</td></tr>';
  if (t) filas += '<tr><td width="18%" bgcolor="#eef0f7" style="font-weight:bold">' +
                  (d.tipo === 'sha' ? 'Comentarios y recomendaciones del inspector' : 'Observaci\u00f3n general') +
                  '</td><td>' + _pdfTexto(t) + '</td></tr>';
  return '<table width="100%" border="1" cellpadding="5" cellspacing="0" ' +
                'style="border-collapse:collapse;border-color:#bbb;margin-top:12px">' +
           filas +
         '</table>';
}
function _pdfFirmas(p, d, tituloInspector) {
  var insp = (d.inspectores || []);
  var res = (d.residentes || []);
  var col = function (titulo, nombre) {
    return '<td width="50%" valign="bottom" style="padding:26px 14px 0">' +
             '<div style="border-top:1px solid #000;padding-top:3px;font-size:9px">' +
               '<b>' + _pdfEsc(titulo) + '</b><br>' +
               (_pdfEsc(nombre) || '&nbsp;') +
             '</div>' +
           '</td>';
  };
  return '<table width="100%" cellpadding="0" cellspacing="0" ' +
                'style="margin-top:14px;page-break-inside:avoid">' +
           '<tr>' +
             col(tituloInspector || 'Ingeniero inspector', insp.join(' \u00b7 ')) +
             col('Ingeniero residente', res.join(' \u00b7 ')) +
           '</tr>' +
           '<tr><td colspan="2" style="padding:10px 14px 0">' + _pdfLeyenda(p) + '</td></tr>' +
         '</table>';
}
function _pdfAvisoSinProyectada() {
  return '<table width="100%" border="1" cellpadding="6" cellspacing="0" ' +
                'style="border-collapse:collapse;border-color:#e0a800;margin-bottom:10px">' +
           '<tr><td bgcolor="#fff8e1" style="font-size:9px">' +
             'En este informe no se registr\u00f3 <b>cantidad proyectada</b> en ninguna subpartida, ' +
             'de modo que <b>no se calcula porcentaje de avance</b>. Se deja constancia de las ' +
             'cantidades ejecutadas y de la evaluaci\u00f3n, que es lo que s\u00ed se verific\u00f3 en sitio.' +
           '</td></tr>' +
         '</table>';
}
function _pdfLeyenda(p) {
  var cuando = Utilities.formatDate(new Date(), 'America/Caracas', "dd/MM/yyyy 'a las' HH:mm");
  var escala = (p.tipo === 'servicios')
    ? 'Respuesta: S\u00cd = existe o est\u00e1 hecho \u00b7 NO = no existe o no est\u00e1 hecho \u00b7 N/A = no aplica en esta torre. ' +
      'NO INSPECCIONADO: el servicio no se verific\u00f3 en esta visita.'
    : (p.tipo === 'urbanismo')
    ? 'Cantidades ejecutadas acumuladas a la fecha, en la unidad de cada partida. Avance = ejecutado / proyectado, solo si Planificaci\u00f3n carg\u00f3 la proyectada. ' +
      'Calidad: B = bueno \u00b7 R = regular \u00b7 M = malo \u00b7 N/A = no aplica. NO INSPECCIONADO: la secci\u00f3n no se verific\u00f3 en esta visita.'
    : (p.tipo === 'sha')
    ? 'Recaudos: S\u00cd = presentado \u00b7 NO = no presentado \u00b7 N/A = no aplica a esta contratista. ' +
      'Hallazgos: Pendiente \u00b7 En proceso \u00b7 Corregido, seg\u00fan lo visto en esta visita. ' +
      'Incidencias: Abierta \u00b7 En seguimiento \u00b7 Cerrada; una incidencia sin cerrar vuelve en la visita siguiente.'
    : 'Evaluaci\u00f3n: B = bueno \u00b7 R = regular \u00b7 M = malo \u00b7 N/A = no aplica o no verificable (no entra en el promedio). ' +
      'NO INSPECCIONADO: el hito no se verific\u00f3. No se le atribuye avance y no entra en ning\u00fan promedio \u2014 no es un cero.';
  if (_pdfCuentaHeredados(p.datos || {})) {
    escala += ' VISITA ANTERIOR: respuesta tra\u00edda del informe anterior de esta torre y no revisada en esta visita.';
  }
  return '<div style="border-top:1px solid #bbb;padding-top:5px;' +
              'font-size:8px;color:#666">' +
           'Documento generado autom\u00e1ticamente a partir del informe archivado ' +
           _pdfEsc(p.numero) + ', el ' + cuando + '. ' + escala +
         '</div>';
}
function _pdfCobertura(medido, ambito) {
  if (!(ambito > 0)) return '0 %';
  var c = Math.floor(medido / ambito * 100);
  return (c === 0 && medido > 0) ? '&lt;1 %' : c + ' %';
}
function _pdfPeso(w) {
  if (!(w > 0)) return '\u2014';
  var x = Math.round(w * 1000) / 10;
  return (x < 0.1 ? '<0,1' : String(x).replace('.', ',')) + ' %';
}
function _pdfAvancePresupuesto(av, d, HS) {
  if (!av) return '';
  var dondeAmbito = (d.ambito === 'torre') ? 'de la torre' : 'del apartamento';
  var fisico = _pdfPromedioSimpleInforme(d, HS);
  var celda = function (titulo, valor, nota) {
    return '<td width="50%" valign="top" style="padding:6px 8px">' +
      '<div style="font-size:9px;color:#555;text-transform:uppercase;letter-spacing:.3px">' + titulo + '</div>' +
      '<div style="font-size:18px;font-weight:bold;color:#1a237e;margin:2px 0">' + valor + '</div>' +
      '<div style="font-size:8px;color:#555">' + nota + '</div></td>';
  };
  var tabla = '<table width="100%" border="1" cellpadding="4" cellspacing="0" ' +
              'style="border-collapse:collapse;border-color:#1a237e;margin-bottom:12px">';
  var titulo = '<tr><td colspan="4" style="font-weight:bold;color:#1a237e;font-size:11px">AVANCE ' +
               (d.ambito === 'torre' ? 'DE LA TORRE' : 'DEL APARTAMENTO') +
               (av.contratista ? ' — ' + _pdfEsc(av.contratista).toUpperCase() : '') + '</td></tr>';
  var cFisico = celda('Avance físico ' + dondeAmbito,
    fisico === null ? '—' : fisico + ' %',
    'Promedio simple de los hitos inspeccionados: todos pesan igual. Es el número que muestra el teléfono.');
  var explica = '<tr><td colspan="4" style="font-size:8px;color:#555">El <b>físico</b> dice cuánto está construido, ' +
    'contando por igual cada hito. El <b>del contrato</b> pesa cada subpartida por lo que cuesta en el presupuesto de la ' +
    'contratista, sin obras preliminares, y solo cuenta lo medido: lo que no se midió no es un cero. Lo que no está en el ' +
    'presupuesto cuenta en el físico y no en el del contrato. Ninguno de los dos es el avance financiero (lo valuado).';
  if (av.sinPresupuesto) {
    var cSin = celda('Avance del contrato', '—',
      'La torre ' + _pdfEsc(av.torre) + ' no tiene presupuesto cargado: este número llega con el presupuesto. Mientras, cada hito lleva su promedio.');
    return tabla + titulo + '<tr>' + cFisico + cSin + '</tr>' + explica + '</td></tr></table>';
  }
  var filas = '';
  HS.forEach(function (h) {
    var x = av.hitos[h.id];
    if (!x || !(x.pesoAmbito > 0)) return;
    var cob = _pdfCobertura(x.pesoMedido, x.pesoAmbito);
    filas += '<tr>' +
      '<td>' + _pdfEsc(String(h.nombre).replace(/^HITO (\d+): /, '$1 · ')) + '</td>' +
      '<td align="right">' + (x.avance === null ? '—' : x.avance + ' %') + '</td>' +
      '<td align="right">' + _pdfPeso(x.pesoAmbito) + '</td>' +
      '<td align="right">' + cob + '</td>' +
    '</tr>';
  });
  var cContrato = celda('Avance del contrato' + (av.contratista ? ' (' + _pdfEsc(av.contratista) + ')' : ''),
    av.avance === null ? '—' : av.avance + ' %',
    av.avance === null
      ? 'Todavía no hay nada medido con peso en el presupuesto.'
      : 'Según el presupuesto, sobre lo medido · lo medido es el <b>' + _pdfCobertura(av.pesoMedido, av.pesoAmbito) + '</b> del peso ' + dondeAmbito +
        (av.provisional ? ' · pesos provisionales (' + _pdfEsc(av.generado || '') + ')' : ''));
  return tabla + titulo +
    '<tr>' + cFisico + cContrato + '</tr>' +
    explica + '</td></tr>' +
    '<tr>' + _pdfTh('', 'Avance del contrato por hito', 'left') + _pdfTh('18%', 'Avance', 'right') +
             _pdfTh('22%', 'Peso en el presupuesto', 'right') + _pdfTh('16%', 'Medido', 'right') + '</tr>' +
    filas +
    '<tr><td colspan="4" style="font-size:8px;color:#555">En cada hito, más abajo, va el promedio simple de sus filas.' +
      (av.provisional ? ' <b>Pesos provisionales</b> hasta que Gerencia Técnica los ratifique.' : '') +
    '</td></tr></table>';
}
function _pdfPromedioSimpleInforme(d, HS) {
  var noInsp = {};
  (d.noInspeccionados || []).forEach(function (h) { noInsp[h] = true; });
  var suma = 0, n = 0;
  HS.forEach(function (h) {
    if (noInsp[h.id]) return;
    var filas = (d.partidas || {})[h.id], extras = (d.partidas || {})[h.id + '_extra'] || [];
    if (!_pdfEsLista(filas)) return;
    var vivas = filas.filter(function (r) { return r && !r.fueraDeAmbito; });
    var prom = _pdfPromedioHito(vivas, extras);
    if (prom !== null) { suma += prom; n++; }
  });
  return n > 0 ? Math.floor(suma / n) : null;
}
function _ceroEscrito(r) {
  var t = String((r && r.ej !== undefined && r.ej !== null) ? r.ej : '').trim().replace(',', '.');
  return t !== '' && parseFloat(t) === 0;
}
function _pdfPctFila(r) {
  if (!r) return null;
  if (String(r.ev || '') === 'N/A') return null;   // no cuenta, no es un cero
  if (r.pct !== undefined && String(r.pct).trim() !== '') {
    var pm = parseFloat(String(r.pct).replace(',', '.'));
    if (!isNaN(pm)) return Math.min(100, Math.max(0, Math.floor(pm)));
  }
  var pr = parseFloat(r.pr);
  var ej = parseFloat(r.ej);
  if (!(pr > 0)) return _ceroEscrito(r) ? 0 : null;   // sin total y sin un cero escrito no hay porcentaje
  if (isNaN(ej) || ej < 0) ej = 0;
  return Math.min(100, Math.round((ej / pr) * 100));
}
function _pdfPromedioHito(filas, extras) {
  var todas = [];
  if (_pdfEsLista(filas))  todas = todas.concat(filas);
  if (_pdfEsLista(extras)) todas = todas.concat(extras);
  if (!todas.length) return null;
  var suma = 0, n = 0;
  for (var i = 0; i < todas.length; i++) {
    var pct = _pdfPctFila(todas[i]);
    if (pct !== null) { suma += pct; n++; }
  }
  return n > 0 ? Math.round(suma / n) : null;
}
function _pdfClaveArea(v) {
  return String(v == null ? '' : v).normalize('NFD').replace(/[\u0300-\u036f]/g, '')
         .trim().toUpperCase().replace(/[^A-Z0-9]/g, '');
}
function _pdfFotosDeFila(fotos, n, area) {
  fotos = fotos || {};
  var porArea = fotos['apto-' + n + '-' + _pdfClaveArea(area)];
  if (porArea && porArea.length) return porArea;
  var pref = 'apto-' + n + '-', out = [];      // 'apto-1-' no casa con 'apto-10-...'
  Object.keys(fotos).forEach(function (clave) {
    if (clave.indexOf(pref) === 0) out = out.concat(fotos[clave]);
  });
  out.sort(function (a, b) { return (a.num || 0) - (b.num || 0); });
  return out;
}
function _pdfFotosPorHito(p) {
  var out = {};
  var lista = p.fotos || [];
  for (var i = 0; i < lista.length; i++) {
    var f = lista[i];
    if (!f || !f.dato) continue;
    var nombre = String(f.nombre || '');
    var corte = nombre.lastIndexOf('-');
    var hito = corte > 0 ? nombre.substring(0, corte) : nombre;
    var num = corte > 0 ? nombre.substring(corte + 1) : '';
    if (!out[hito]) out[hito] = [];
    out[hito].push({ dato: f.dato, num: parseInt(num, 10) || (out[hito].length + 1),
                     pie: 'Fotograf\u00eda ' + (num || (out[hito].length + 1)) });
  }
  return out;
}
function _pdfEsLista(v) {
  return Object.prototype.toString.call(v) === '[object Array]';
}
function _pdfEsc(v) {
  return String(v === undefined || v === null ? '' : v)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
function _pdfTexto(v) {
  return _pdfEsc(v).replace(/\r?\n/g, '<br>');
}
function _pdfHeredado(h) {
  if (!h) return '';
  return '<div style="font-size:7px;color:#92400e;white-space:nowrap">visita anterior</div>';
}
function _pdfCuentaHeredados(d) {
  var n = 0;
  (d.general || []).forEach(function (g) {
    (g.items || []).forEach(function (it) { if (it.heredado && it.sn) n++; });
  });
  (d.apartamentos || []).forEach(function (a) { if (a.heredado) n++; });
  (d.incidencias || []).forEach(function (x) { if (x.heredado) n++; });
  return n;
}
function _pdfEtiquetaLugar(p, etiqueta) {
  var u = (p.datos || {}).ubicacion;
  return (u && u.modo && u.modo !== 'una') ? 'Ubicaci\u00f3n' : etiqueta;
}
function _pdfLugar(p) {
  var u = (p.datos || {}).ubicacion || {};
  var otras = u.otras || [];
  if (String(p.torre || '').trim().toUpperCase() === 'ZONA') {
    return 'Toda la zona' + (otras.length ? ' \u00b7 tambi\u00e9n ' + otras.join(' \u00b7 ') : '');
  }
  if (u.modo === 'varias' && otras.length) return p.torre + ' (principal) \u00b7 ' + otras.join(' \u00b7 ');
  return p.torre;
}
function _pdfHtmlServicios(p) {
  var d = p.datos || {};
  var fotos = _pdfFotosPorHito(p);            // agrupa por prefijo: srv_x, apto-N-...
  var noInsp = {};
  (d.noInspeccionados || []).forEach(function (id) { noInsp[id] = true; });
  var cuerpo = '';
  (d.general || []).forEach(function (g) {
    cuerpo += _pdfServicio(g, fotos[g.id] || [], !!noInsp[g.id]);
  });
  if ((d.apartamentos || []).length) {
    cuerpo += '<div style="' + PDF_BARRA + ';' + PDF_REGLA + ';margin:14px 0 6px;font-size:12px">' +
              'APARTAMENTOS Y \u00c1REAS COMUNES</div>';
    (d.apartamentos || []).forEach(function (a, k) {
      cuerpo += _pdfApartamento(a, _pdfFotosDeFila(fotos, k + 1, a.apto));
    });
  }
  return '<html><head><meta charset="utf-8"></head>' +
    '<body style="font-family:Arial,Helvetica,sans-serif;color:#000;font-size:10px">' +
      _pdfMembrete(p, d, 'INFORME DE INSPECCI\u00d3N DE SERVICIOS P\u00daBLICOS') +
      _pdfIdentificacionServicios(p, d) +
      cuerpo +
      _pdfObservacionGeneral(d) +
      _pdfFirmas(p, d) +
      _pdfMinutas(p) +
    '</body></html>';
}
function _pdfIdentificacionServicios(p, d) {
  var sector = (typeof _nombreDeSector === 'function') ? _nombreDeSector(p.sector) : (p.sector || '');
  var pares = [
    ['Fecha de inspecci\u00f3n', d.fecha],
    ['Sector', sector],
    [_pdfEtiquetaLugar(p, 'Torre'), _pdfLugar(p)],
    ['Empresa ejecutora', d.empresa],
    ['Ingeniero(s) residente(s)', (d.residentes || []).join(' \u00b7 ')],
    ['Ingeniero(s) inspector(es)', (d.inspectores || []).join(' \u00b7 ')],
    ['Versi\u00f3n', _versionDelInforme(d)],   // r50: preliminar (campo) o definitiva (cerrada en oficina)
    ['Estatus de la obra', (d.estatus || []).join(' \u00b7 ')],
    ['Apartamentos visitados', String((d.apartamentos || []).length)]
  ];
  var filas = '';
  for (var i = 0; i < pares.length; i += 2) {
    filas += '<tr>' + (pares[i + 1]
      ? _pdfCeldaEtiqueta(pares[i][0]) + _pdfCeldaValor(pares[i][1]) +
        _pdfCeldaEtiqueta(pares[i + 1][0]) + _pdfCeldaValor(pares[i + 1][1])
      : _pdfCeldaEtiqueta(pares[i][0]) + _pdfCeldaValor(pares[i][1], 3)) + '</tr>';
  }
  return '<table width="100%" border="1" cellpadding="4" cellspacing="0" ' +
              'style="border-collapse:collapse;border-color:#bbb;margin-bottom:12px">' + filas + '</table>';
}
function _pdfRespuesta(sn) {
  return sn === 'SI' ? 'S\u00cd' : sn === 'NO' ? 'NO' : sn === 'NA' ? 'N/A' : '\u2014';
}
function _pdfServicio(g, fotos, noInspeccionado) {
  var html = '<div style="' + PDF_BARRA + ';' + PDF_REGLA + ';margin:12px 0 4px">' +
             _pdfEsc(g.nombre) +
             (noInspeccionado ? ' <span style="' + PDF_APAGADO + '">\u2014 NO INSPECCIONADO</span>' : '') +
             '</div>';
  if (noInspeccionado) return html;
  var items = (g.items || []).filter(function (it) { return it.sn || it.obs || it.agregado; });
  if (items.length) {
    html += '<table width="100%" border="1" cellpadding="3" cellspacing="0" ' +
                 'style="border-collapse:collapse;border-color:#bbb">' +
            '<tr>' + _pdfTh('5%', '#') + _pdfTh('45%', '\u00cdtem', 'left') +
                     _pdfTh('10%', 'Resp.') + _pdfTh('40%', 'Observaci\u00f3n', 'left') + '</tr>';
    items.forEach(function (it, i) {
      html += '<tr>' +
        '<td align="center">' + (it.agregado ? '+' : (i + 1)) + '</td>' +
        '<td>' + _pdfEsc(it.nombre) + (it.agregado ? ' <i style="color:#555">(agregado en campo)</i>' : '') + '</td>' +
        '<td align="center"><b>' + _pdfRespuesta(it.sn) + '</b>' + _pdfHeredado(it.heredado) + '</td>' +
        '<td>' + _pdfTexto(it.obs || '') + '</td></tr>';
    });
    html += '</table>';
  } else {
    html += '<div style="color:#666;font-style:italic;margin:2px 0 4px">Sin \u00edtems contestados.</div>';
  }
  if (g.obs) html += _pdfObsHito(g.obs);
  html += _pdfFotos(_pdfConPies(fotos, g.fotos));
  return html;
}
function _pdfApartamento(a, fotos) {
  var piso = (a.piso === 'PB') ? 'Planta Baja' : String(a.piso || '').replace(/^P(\d+)$/, 'Piso $1');
  var titulo = (piso ? piso + ' \u00b7 ' : '') + 'Apto ' + _pdfEsc(a.apto || '\u2014');
  var html = '<div style="font-weight:bold;margin:8px 0 3px;font-size:10.5px">' + titulo +
             (a.heredado ? ' <span style="font-weight:normal;font-size:8px;color:#92400e">(visita anterior, sin revisar)</span>' : '') +
             '</div>';
  var campos = a.campos || {};
  var filas = '';
  Object.keys(campos).forEach(function (c) {
    var v = campos[c];
    if (v === '' || v === null || v === undefined) return;
    var partes = c.split('__');
    var esResp = (v === 'SI' || v === 'NO' || v === 'NA');
    filas += '<tr><td>' + _pdfEsc(_servicioDeApto(partes[0])) + '</td>' +
             '<td>' + _pdfEsc(partes[1] || c) + '</td>' +
             '<td align="center">' + (esResp ? '<b>' + _pdfRespuesta(v) + '</b>'
                                             : (partes[1] === 'Observaciones' ? _pdfTexto(v) : _pdfEsc(v) + ' pza')) +
             '</td></tr>';
  });
  html += filas
    ? '<table width="100%" border="1" cellpadding="3" cellspacing="0" style="border-collapse:collapse;border-color:#bbb">' +
      '<tr>' + _pdfTh('30%', 'Servicio', 'left') + _pdfTh('40%', 'Punto', 'left') + _pdfTh('30%', 'Valor') + '</tr>' +
      filas + '</table>'
    : '<div style="color:#666;font-style:italic">Sin datos.</div>';
  html += _pdfFotos(_pdfConPies(fotos, a.fotos));
  return html;
}
function _pdfHtmlSha(p) {
  var d = p.datos || {};
  d.tipo = 'sha';
  var fotos = _pdfFotosPorHito(p);
  var noInsp = {};
  (d.noInspeccionados || []).forEach(function (id) { noInsp[id] = true; });
  var cuerpo = '';
  (d.general || []).forEach(function (g) {
    cuerpo += _pdfServicio(g, fotos[g.id] || [], !!noInsp[g.id]);
  });
  cuerpo += '<div style="' + PDF_BARRA + ';' + PDF_REGLA + ';margin:14px 0 6px;font-size:12px">' +
            'HALLAZGOS DE CAMPO</div>';
  if ((d.apartamentos || []).length) {
    (d.apartamentos || []).forEach(function (a, k) {
      cuerpo += _pdfHallazgo(a, _pdfFotosDeFila(fotos, k + 1, a.apto), k + 1);
    });
  } else {
    cuerpo += '<div style="color:#666;font-style:italic;margin:2px 0 4px">Sin hallazgos de campo registrados en esta visita.</div>';
  }
  if ((d.incidencias || []).length) {
    cuerpo += '<div style="' + PDF_BARRA + ';' + PDF_REGLA + ';margin:14px 0 6px;font-size:12px">' +
              'INCIDENCIAS \u00b7 ACCIDENTES</div>';
    (d.incidencias || []).forEach(function (x, k) {
      cuerpo += _pdfIncidencia(x, p, d, fotos['inc-' + (k + 1)] || [], k + 1);
    });
  }
  cuerpo += _pdfObstaculos(d, _pdfConPies(fotos['obst'] || [], d.fotosObstaculos));
  var generales = _pdfConPies(fotos['general'] || [], d.fotosGenerales);
  if (generales.length) {
    cuerpo += '<div style="' + PDF_BARRA + ';' + PDF_REGLA + ';margin:14px 0 6px;font-size:12px">' +
              'FOTOGRAF\u00cdAS GENERALES DE LA VISITA</div>' + _pdfFotos(generales);
  }
  return '<html><head><meta charset="utf-8"></head>' +
    '<body style="font-family:Arial,Helvetica,sans-serif;color:#000;font-size:10px">' +
      _pdfMembrete(p, d, 'INFORME DE INSPECCI\u00d3N SHA \u00b7 SEGURIDAD, HIGIENE Y AMBIENTE') +
      _pdfIdentificacionSha(p, d) +
      cuerpo +
      _pdfObservacionGeneral(d) +
      _pdfFirmas(p, d, 'Inspector SHA') +
      _pdfMinutas(p) +
    '</body></html>';
}
function _obstaculoConDato(o) {
  var hay = function (v) { return v !== undefined && v !== null && String(v).trim() !== ''; };
  return !!o && (hay(o.retirado) || hay(o.queda) || hay(o.pct) || hay(o.obs));
}
function _pdfObstaculos(d, fotos) {
  var filas = (d.obstaculos || []).filter(_obstaculoConDato);
  if (!filas.length && !(fotos || []).length) return '';
  var cuerpo = '';
  filas.forEach(function (o) {
    var esPct = o.mide === 'pct';
    var pct = parseFloat(o.pct);
    var ret = esPct ? (isNaN(pct) ? '' : pct + ' %') : _pdfEsc(o.retirado);
    var queda = esPct ? (isNaN(pct) ? '' : (100 - pct) + ' %') : _pdfEsc(o.queda);
    cuerpo += '<tr><td>' + _pdfEsc(o.nombre || o.id) + '</td>' +
              '<td align="center">' + (ret === '' ? '\u2014' : ret) + '</td>' +
              '<td align="center">' + (queda === '' ? '\u2014' : queda) + '</td>' +
              '<td>' + (_pdfTexto(o.obs) || '&nbsp;') + '</td></tr>';
  });
  return '<div style="' + PDF_BARRA + ';' + PDF_REGLA + ';margin:14px 0 6px;font-size:12px">DESMONTAJE DE OBST\u00c1CULOS</div>' +
    (filas.length
      ? '<table width="100%" border="1" cellpadding="4" cellspacing="0" style="border-collapse:collapse;border-color:#bbb">' +
          '<tr>' + _pdfTh('30%', 'Obst\u00e1culo', 'left') + _pdfTh('15%', 'Retirado a la fecha', '') +
                   _pdfTh('15%', 'Queda por retirar', '') + _pdfTh('', 'Observaci\u00f3n', 'left') + '</tr>' +
          cuerpo +
          '<tr><td colspan="4" style="font-size:8px;color:#555">Lo retirado es el acumulado a la fecha, no solo lo de esta visita. ' +
            'La chatarra va en porcentaje, a criterio del inspector.</td></tr>' +
        '</table>'
      : '') +
    _pdfFotos(fotos);
}
function _pdfIdentificacionSha(p, d) {
  var sector = (typeof _nombreDeSector === 'function') ? _nombreDeSector(p.sector) : (p.sector || '');
  var her = _pdfCuentaHeredados(d);
  var pares = [
    ['Fecha de inspecci\u00f3n', d.fecha],
    ['Sector', sector],
    [_pdfEtiquetaLugar(p, 'Torre'), _pdfLugar(p)],
    ['Empresa ejecutora', d.empresa],
    ['Ingeniero(s) residente(s)', (d.residentes || []).join(' \u00b7 ')],
    ['Inspector(es) SHA', (d.inspectores || []).join(' \u00b7 ')],
    ['Versi\u00f3n', _versionDelInforme(d)],   // r50: preliminar (campo) o definitiva (cerrada en oficina)
    ['Estatus general de la inspecci\u00f3n', (d.estatus || []).join(' \u00b7 ') || '\u2014'],
    ['Hallazgos de campo', String((d.apartamentos || []).length)],
    ['Incidencias (accidentes)', String((d.incidencias || []).length)],
    ['Respuestas de la visita anterior sin revisar', her ? String(her) : 'ninguna']
  ];
  var filas = '';
  for (var i = 0; i < pares.length; i += 2) {
    filas += '<tr>' + (pares[i + 1]
      ? _pdfCeldaEtiqueta(pares[i][0]) + _pdfCeldaValor(pares[i][1]) +
        _pdfCeldaEtiqueta(pares[i + 1][0]) + _pdfCeldaValor(pares[i + 1][1])
      : _pdfCeldaEtiqueta(pares[i][0]) + _pdfCeldaValor(pares[i][1], 3)) + '</tr>';
  }
  var accion = String(d.accion || '').trim();
  if (accion) {
    filas += '<tr>' + _pdfCeldaEtiqueta('Acci\u00f3n por el rechazo') +
      '<td colspan="3" style="color:#b91c1c;font-weight:bold">' + _pdfEsc(accion) +
      (String(d.accion_det || '').trim() ? ' \u00b7 <span style="font-weight:normal;color:#000">' + _pdfEsc(d.accion_det) + '</span>' : '') +
      '</td></tr>';
  }
  return '<table width="100%" border="1" cellpadding="4" cellspacing="0" ' +
              'style="border-collapse:collapse;border-color:#bbb;margin-bottom:12px">' + filas + '</table>';
}
function _pdfHallazgo(a, fotos, n) {
  var campos = a.campos || {};
  var desc = '', st = '', sol = '', resp = '';
  Object.keys(campos).forEach(function (c) {
    var etiqueta = c.split('__')[1] || c;
    if (/estatus/i.test(etiqueta)) st = campos[c];
    else if (/descripci/i.test(etiqueta)) desc = campos[c];
    else if (/^soluci/i.test(etiqueta)) sol = campos[c];             // r38 (v114): las dos columnas de la matriz de SHA
    else if (/^responsable/i.test(etiqueta)) resp = campos[c];
  });
  var html = '<div style="font-weight:bold;margin:8px 0 3px;font-size:10.5px">' +
             n + '. ' + _pdfEsc(a.apto || '\u00c1rea sin indicar') +
             (a.heredado ? ' <span style="font-weight:normal;font-size:8px;color:#92400e">(visita anterior, sin revisar)</span>' : '') +
             '</div>' +
    '<table width="100%" border="1" cellpadding="4" cellspacing="0" style="border-collapse:collapse;border-color:#bbb">' +
      '<tr><td width="22%" bgcolor="#eef0f7" style="font-weight:bold">Hallazgo</td><td>' + (_pdfTexto(desc) || '\u2014') + '</td></tr>' +
      '<tr><td bgcolor="#eef0f7" style="font-weight:bold">Acci\u00f3n correctiva / estatus</td><td><b>' + (_pdfEsc(st) || '\u2014') + '</b></td></tr>' +
      (String(sol || '').trim() ? '<tr><td bgcolor="#eef0f7" style="font-weight:bold">Soluci\u00f3n</td><td>' + _pdfTexto(sol) + '</td></tr>' : '') +
      (String(resp || '').trim() ? '<tr><td bgcolor="#eef0f7" style="font-weight:bold">Responsable del correctivo</td><td>' + _pdfEsc(resp) + '</td></tr>' : '') +
    '</table>';
  html += _pdfFotos(_pdfConPies(fotos, a.fotos));
  return html;
}
var PDF_SEMAFORO = { 'Abierta': '#dc2626', 'En seguimiento': '#d97706', 'Cerrada': '#16a34a' };
function _pdfIncidencia(x, p, d, fotos, n) {
  var sector = (typeof _nombreDeSector === 'function') ? _nombreDeSector(p.sector) : (p.sector || '');
  var estado = String(x.estado || '').trim();
  var color = PDF_SEMAFORO[estado] || '#475569';
  var html = '<div style="font-weight:bold;margin:8px 0 3px;font-size:10.5px">' +
             n + '. ' + _pdfEsc(x.tipo || 'Tipo sin indicar') +
             ' <span style="font-weight:normal;font-size:8px;color:#666">\u00b7 ' + _pdfEsc(x.fecha || d.fecha || '') + '</span>' +
             (x.heredado ? ' <span style="font-weight:normal;font-size:8px;color:#92400e">(visita anterior, sin revisar)</span>' : '') +
             ' <span style="float:right;background:' + color + ';color:#fff;font-size:8px;padding:2px 8px;border-radius:9px">\u25cf ' + (_pdfEsc(estado) || 'sin estado') + '</span>' +
             '</div>' +
    '<table width="100%" border="1" cellpadding="4" cellspacing="0" style="border-collapse:collapse;border-color:#bbb">' +
      '<tr><td width="22%" bgcolor="#eef0f7" style="font-weight:bold">Convenio / sector</td><td width="28%">' + _pdfEsc((d.convenio || '') + (sector ? ' \u00b7 ' + sector : '')) + '</td>' +
          '<td width="22%" bgcolor="#eef0f7" style="font-weight:bold">Empresa</td><td>' + _pdfEsc(d.empresa || '') + '</td></tr>' +
      '<tr><td bgcolor="#eef0f7" style="font-weight:bold">Fecha del accidente</td><td>' + _pdfEsc(x.fecha || '\u2014') + '</td>' +
          '<td bgcolor="#eef0f7" style="font-weight:bold">Ing. residente</td><td>' + _pdfEsc((d.residentes || []).join(' \u00b7 ')) + '</td></tr>' +
      '<tr><td bgcolor="#eef0f7" style="font-weight:bold">Inspector SHA</td><td colspan="3">' + _pdfEsc((d.inspectores || []).join(' \u00b7 ')) + '</td></tr>' +
      '<tr><td bgcolor="#eef0f7" style="font-weight:bold">Tipo de accidente</td><td colspan="3"><b>' + (_pdfEsc(x.tipo) || '\u2014') + '</b></td></tr>' +
      '<tr><td bgcolor="#eef0f7" style="font-weight:bold">Notas de campo</td><td colspan="3">' + (_pdfTexto(x.notas) || '\u2014') + '</td></tr>' +
      '<tr><td bgcolor="#eef0f7" style="font-weight:bold">Acciones a tomar</td><td colspan="3">' + (_pdfTexto(x.acciones) || '\u2014') + '</td></tr>' +
      '<tr><td bgcolor="#eef0f7" style="font-weight:bold">Estado</td><td colspan="3" style="color:' + color + ';font-weight:bold">' + (_pdfEsc(estado) || '\u2014') + '</td></tr>' +
    '</table>';
  html += _pdfFotos(_pdfConPies(fotos, x.fotos));
  return html;
}
function _pdfHtmlUrbanismo(p) {
  var d = p.datos || {};
  d.tipo = 'urbanismo';
  var fotos = _pdfFotosPorHito(p);
  var noInsp = {};
  (d.noInspeccionados || []).forEach(function (id) { noInsp[id] = true; });
  var cuerpo = '';
  (d.general || []).forEach(function (g) {
    cuerpo += _pdfSeccionUrbanismo(g, fotos[g.id] || [], !!noInsp[g.id]);
  });
  return '<html><head><meta charset="utf-8"></head>' +
    '<body style="font-family:Arial,Helvetica,sans-serif;color:#000;font-size:10px">' +
      _pdfMembrete(p, d, 'INFORME DE INSPECCIÓN DE URBANISMO') +
      _pdfIdentificacionUrbanismo(p, d) +
      cuerpo +
      _pdfObservacionGeneral(d) +
      _pdfFirmas(p, d, 'Inspector') +
      _pdfMinutas(p) +
    '</body></html>';
}
function _pdfIdentificacionUrbanismo(p, d) {
  var sector = (typeof _nombreDeSector === 'function') ? _nombreDeSector(p.sector) : (p.sector || '');
  var her = _pdfCuentaHeredados(d);
  var noInsp = (d.noInspeccionados || []).map(function (id) {
    var g = (d.general || []).filter(function (x) { return x.id === id; })[0];
    var libre = String(id).replace(/^urb_(x_)?/, '').replace(/_/g, ' ');
    return g ? String(g.nombre || id).replace(/^\d+\.\s*/, '') : libre.charAt(0).toUpperCase() + libre.slice(1);
  });
  var pares = [
    ['Fecha de inspección', d.fecha],
    ['Sector', sector],
    [_pdfEtiquetaLugar(p, 'Manzana / lote'), _pdfLugar(p)],
    ['Empresa ejecutora', d.empresa],
    ['Ingeniero(s) residente(s)', (d.residentes || []).join(' · ')],
    ['Inspector(es)', (d.inspectores || []).join(' · ')],
    ['Versi\u00f3n', _versionDelInforme(d)],   // r50: preliminar (campo) o definitiva (cerrada en oficina)
    ['Estatus de la obra', (d.estatus || []).join(' · ') || '—'],
    ['Secciones no inspeccionadas', noInsp.length ? noInsp.join(' · ') : 'ninguna'],
    ['Cantidades de la visita anterior sin revisar', her ? String(her) : 'ninguna']
  ];
  var filas = '';
  for (var i = 0; i < pares.length; i += 2) {
    filas += '<tr>' + (pares[i + 1]
      ? _pdfCeldaEtiqueta(pares[i][0]) + _pdfCeldaValor(pares[i][1]) +
        _pdfCeldaEtiqueta(pares[i + 1][0]) + _pdfCeldaValor(pares[i + 1][1])
      : _pdfCeldaEtiqueta(pares[i][0]) + _pdfCeldaValor(pares[i][1], 3)) + '</tr>';
  }
  return '<table width="100%" border="1" cellpadding="4" cellspacing="0" ' +
              'style="border-collapse:collapse;border-color:#bbb;margin-bottom:12px">' + filas + '</table>';
}
var PDF_CALIDAD = { B: 'B', R: 'R', M: 'M', NA: 'N/A' };
function _pdfSeccionUrbanismo(g, fotos, noInspeccionado) {
  var html = '<div style="' + PDF_BARRA + ';' + PDF_REGLA + ';margin:14px 0 6px;font-size:12px">' +
             _pdfEsc(g.nombre) + (noInspeccionado ? ' — NO INSPECCIONADO' : '') + '</div>';
  if (noInspeccionado) return html;
  var items = (g.items || []).filter(function (it) { return it.sn || it.cant || it.pr || String(it.obs || '').trim(); });
  if (!items.length && !String(g.obs || '').trim() && !fotos.length) return '';
  if (!items.length) {
    html += '<div style="color:#666;font-style:italic;margin:2px 0 4px">Sin partidas registradas en esta visita.</div>';
  } else {
    html += '<table width="100%" border="1" cellpadding="4" cellspacing="0" style="border-collapse:collapse;border-color:#bbb">' +
      '<tr bgcolor="#eef0f7" style="font-weight:bold"><td width="4%">#</td><td width="30%">Partida</td>' +
      '<td width="14%" align="right">Ejecutado</td><td width="12%" align="right">Proyectado</td><td width="8%" align="center">Avance</td>' +
      '<td width="8%" align="center">Calidad</td><td>Observación</td></tr>';
    items.forEach(function (it, k) {
      var c = parseFloat(it.cant), pr = parseFloat(it.pr);
      var av = (pr > 0 && c >= 0) ? Math.round(c / pr * 100) + ' %' : '';
      html += '<tr' + (it.heredado ? ' style="color:#92400e"' : '') + '>' +
        '<td>' + (k + 1) + '</td>' +
        '<td>' + _pdfEsc(it.nombre) + (it.agregado ? ' <span style="font-size:8px;color:#666">(agregada en campo)</span>' : '') +
                 (it.heredado ? ' <span style="font-size:8px">(visita anterior, sin revisar)</span>' : '') + '</td>' +
        '<td align="right">' + (it.cant ? _pdfEsc(it.cant) + ' ' + _pdfEsc(it.ud || '') : '—') + '</td>' +
        '<td align="right">' + (it.pr ? _pdfEsc(it.pr) + ' ' + _pdfEsc(it.ud || '') : '—') + '</td>' +
        '<td align="center">' + av + '</td>' +
        '<td align="center"><b>' + (PDF_CALIDAD[it.sn] || '—') + '</b></td>' +
        '<td>' + _pdfTexto(it.obs || '') + '</td></tr>' +
        _pdfCamionesUrbanismo(it);
    });
    html += '</table>';
  }
  html += _pdfObsHito(g.obs || '') + _pdfFotos(_pdfConPies(fotos, g.fotos));
  return html;
}
function _pdfCamionesUrbanismo(it) {
  var cs = it.camiones || [];
  if (!cs.length) return '';
  var hoy = 0;
  var lista = cs.map(function (c, k) {
    var m3 = parseFloat(c.m3) || 0, v = parseInt(c.viajes, 10) || 0;
    hoy += m3 * v;
    return 'Cami\u00f3n ' + (k + 1) + (c.placa ? ' (' + _pdfEsc(c.placa) + ')' : '') + ': ' +
           _pdfEsc(c.m3 || '0') + ' m\u00b3 \u00d7 ' + v + ' viaje(s)';
  }).join(' \u00b7 ');
  hoy = Math.round(hoy * 100) / 100;
  var cuenta = 'Hoy: ' + hoy + ' m\u00b3' +
    (it.base ? ' \u00b7 acumulado anterior ' + _pdfEsc(it.base) + ' m\u00b3' : '');
  return '<tr><td></td><td colspan="6" style="font-size:9px;color:#334155">' +
           '<b>Camiones:</b> ' + lista + '<br>' + cuenta + '</td></tr>';
}
  window.VistaPrevia = {
    huella: 'ac06aff313',
    tipos: ['servicios', 'sha', 'urbanismo'],
    html: function (p) {
      var f = { servicios: _pdfHtmlServicios, sha: _pdfHtmlSha, urbanismo: _pdfHtmlUrbanismo }[p && p.tipo];
      if (!f) throw new Error('Sin vista previa para el tipo ' + (p && p.tipo));
      return f(p);
    }
  };
})();
